### ISSUE TITLE
多线程持续调用播放直播流，同时播放多路视频流两到三天后，所有的直播流都打不开了。

### ISSUE THREAD

**Issue by gujianghua** [648540858/wvp-GB28181-pro#102]
java.lang.RuntimeException: ssrc已经用完
	at com.genersoft.iot.vmp.gb28181.session.SsrcUtil.getSN(SsrcUtil.java:75) ~[classes!/:2.3.5.RELEASE]
	at com.genersoft.iot.vmp.gb28181.session.SsrcUtil.getPlaySsrc(SsrcUtil.java:46) ~[classes!/:2.3.5.RELEASE]
	at com.genersoft.iot.vmp.gb28181.session.VideoStreamSessionManager.createPlaySsrc(VideoStreamSessionManager.java:21) ~[classes!/:2.3.5.RELEASE]
	at com.genersoft.iot.vmp.gb28181.transmit.cmd.impl.SIPCommander.playStreamCmd(SIPCommander.java:295) ~[classes!/:2.3.5.RELEASE]
	at com.genersoft.iot.vmp.vmanager.play.PlayController.play(PlayController.java:73) ~[classes!/:2.3.5.RELEASE]
	at jdk.internal.reflect.GeneratedMethodAccessor265.invoke(Unknown Source) ~[na:na]

**Comment by 648540858** [comment]
可以把你的测试方法描述下吗

**Comment by gujianghua** [comment]
用python写的程序，同时调用多路设备的直播流。总共调用了1000个设备，两天左右所有直播流都不能播放了。

**Comment by gujianghua** [comment]
在1000个设备循环调用播放流，每次最多同时播放5到6路设备。

**Comment by 648540858** [comment]
在你的设备切换之间加个延时，服务可能释放不了那么快。

**Comment by gujianghua** [comment]
如果是需要加延时的话，那应该在一天内大量调用的时候就报错了呀，但是他运行时间长了才报错，是不是所有服务都没有释放掉呢。

**Comment by 648540858** [comment]
你使用的最新的代码吗？ 最新的代码我解决过ssrc释放的问题。

**Comment by gujianghua** [comment]
是的 ，用的你改过的这个
![image](https://user-images.githubusercontent.com/82638990/119761088-c493c300-bedd-11eb-8d1d-5e4bff5066ae.png)

**Comment by 648540858** [comment]
不是当前最新的代码？

**Comment by gujianghua** [comment]
不是当前最新的

**Comment by 648540858** [comment]
更新再试试， 不是你说的这个提交点

**Comment by gujianghua** [comment]
好的 谢谢 ，最新的是在这个分支吧

**Comment by 648540858** [comment]
是的

**Comment by gujianghua** [comment]
最新代码 生成的jar包运行报错了 。麻烦看一下呢![image](https://user-images.githubusercontent.com/82638990/119924768-c70e1f80-bfa6-11eb-8f4f-c3a1a494fee3.png)![image](https://user-images.githubusercontent.com/82638990/119924719-b198f580-bfa6-11eb-963d-e5b584e45f13.png)

**Comment by 648540858** [comment]
请使用新的配置文件，不要拿旧的直接用。

**Comment by gujianghua** [comment]
好的 谢谢

**Comment by 648540858** [comment]
你的测试结果方便的时候给我个反馈吧
