### ISSUE TITLE
SIPProcessorObserver引起OOM

### ISSUE THREAD

**Issue by pspburner** [648540858/wvp-GB28181-pro#1046]
**环境信息:**

 - 1. 部署方式 wvp-prp + zlm都是编译部署
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 默认
 - 4. 是否是公网部署 是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间 2022/12/3

**描述错误**
出现大量如下报错信息，最后报OOM
`2023-08-28 14:44:50.543 [wvp-8520] WARN  c.g.iot.vmp.gb28181.transmit.SIPProcessorObserver:119 - 接收到失败的response响应！status：400,message:Bad Request`

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
2023-08-28 14:44:48.239 [wvp-8530] WARN  c.g.iot.vmp.gb28181.transmit.SIPProcessorObserver:119 - 接收到失败的response响应！status：400,message:Bad Request
2023-08-28 14:44:50.542 [wvp-8529] WARN  c.g.iot.vmp.gb28181.transmit.SIPProcessorObserver:119 - 接收到失败的response响应！status：400,message:Bad Request
2023-08-28 14:44:48.986 [wvp-8531] WARN  c.g.iot.vmp.gb28181.transmit.SIPProcessorObserver:119 - 接收到失败的response响应！status：400,message:Bad Request
2023-08-28 14:44:50.543 [wvp-8520] WARN  c.g.iot.vmp.gb28181.transmit.SIPProcessorObserver:119 - 接收到失败的response响应！status：400,message:Bad Request
2023-08-28 14:44:55.804 [wvp-8531] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler:39 - Unexpected exception occurred invoking async method: public void com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processResponse(javax.sip.ResponseEvent)
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.StringLatin1.newString(StringLatin1.java:715)
	at java.base/java.lang.String.substring(String.java:1879)
	at com.alibaba.fastjson2.JSONReaderASCII.readString(JSONReaderASCII.java:1390)
	at com.alibaba.fastjson2.reader.ObjectReader_2.readObject(Unknown Source)
	at com.alibaba.fastjson2.reader.ObjectReader_1.readObject(Unknown Source)
	at com.alibaba.fastjson2.reader.ObjectReaderImplObject.readObject(ObjectReaderImplObject.java:121)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:802)
	at com.genersoft.iot.vmp.utils.redis.FastJsonRedisSerializer.deserialize(FastJsonRedisSerializer.java:41)
	at org.springframework.data.redis.core.AbstractOperations.deserializeValue(AbstractOperations.java:360)
	at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:62)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:191)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:97)
	at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:54)
	at com.genersoft.iot.vmp.utils.redis.RedisUtil.get(RedisUtil.java:111)
	at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl.getOne(MediaServerServiceImpl.java:283)
	at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl.releaseSsrc(MediaServerServiceImpl.java:182)
	at com.genersoft.iot.vmp.gb28181.transmit.cmd.impl.SIPCommander.lambda$playStreamCmd$1(SIPCommander.java:346)
	at com.genersoft.iot.vmp.gb28181.transmit.cmd.impl.SIPCommander$$Lambda$1318/0x0000000840a9cc40.response(Unknown Source)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPSender.lambda$transmitRequest$0(SIPSender.java:69)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPSender$$Lambda$1320/0x0000000840a9c440.response(Unknown Source)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processResponse(SIPProcessorObserver.java:126)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$$Lambda$1307/0x0000000840a9f840.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
```

**Comment by Kender0221** [comment]
贴代码没什么用
请自行检查：
1、配置文件是否正确、端口视口开启、防火墙相关问题。
2、zlm跟wvp版本问题

**Comment by mengxing2017** [comment]
2022/12/3的代码，老代码没人维护了，使用有问题就更新到最新版呗
