### ISSUE TITLE
移动设备位置上报 Column 'channel_id' cannot be null

### ISSUE THREAD

**Issue by godlike10** [648540858/wvp-GB28181-pro#1054]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ...
 - 3. 端口开放情况
 - 4. 是否是公网部署 
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
描述下您遇到的问题
接入一个移动设备，记录位置信息，表wvp_device_mobile_position 里面的字段channel_id是非空的。
但是系统中有几个地方插入这个记录的时候都没有给channelid赋值
![image](https://github.com/648540858/wvp-GB28181-pro/assets/6766502/b9facc51-407f-49b9-b2d3-5c6bfe214c5e)
比如这里这一行是我加入的，还有几个地方都有同样的问题。

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'channel_id' cannot be null
### The error may exist in com/genersoft/iot/vmp/storager/dao/DeviceMobilePositionMapper.java (best guess)
### The error may involve com.genersoft.iot.vmp.storager.dao.DeviceMobilePositionMapper.insertNewPosition-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO wvp_device_mobile_position (device_id,channel_id, device_name,time,longitude,latitude,altitude,speed,direction,report_source,longitude_gcj02,latitude_gcj02,longitude_wgs84,latitude_wgs84,create_time)VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'channel_id' cannot be null
; Column 'channel_id' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'channel_id' cannot be null
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:87)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy87.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:272)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	at com.sun.proxy.$Proxy107.insertNewPosition(Unknown Source)
	at com.genersoft.iot.vmp.storager.impl.VideoManagerStorageImpl.insertMobilePosition(VideoManagerStorageImpl.java:471)
	at com.genersoft.iot.vmp.storager.impl.VideoManagerStorageImpl$$FastClassBySpringCGLIB$$b5684f89.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
	at com.genersoft.iot.vmp.storager.impl.VideoManagerStorageImpl$$EnhancerBySpringCGLIB$$9a3a668e.insertMobilePosition(<generated>)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.notify.cmd.AlarmNotifyMessageHandler.lambda$handForDevice$0(AlarmNotifyMessageHandler.java:161)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'channel_id' cannot be null
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64)
	at com.sun.proxy.$Proxy184.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	... 17 common frames omitted
2023-09-05 15:11:35.265 [wvp-1] WARN  c.g.i.v.g.t.e.r.i.m.n.c.AlarmNotifyMessageHandler:212 - [收到报警通知] 发现未处理的异常, 

日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
已修复
