### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by MetSystem** [648540858/wvp-GB28181-pro#1064]
**环境信息:**

 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows
 - 3. 端口开放情况
 - 4. 是否是公网部署  
 - 5. 是否使用https 
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间

**描述错误**
1.第一次启动正常，
2.改前端返回流地址，再启动就报redis错误

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
日志内容放这里， 文件的话请直接上传
aused by: io.lettuce.core.RedisCommandInterruptedException: Command interrupted
       at io.lettuce.core.protocol.AsyncCommand.await(AsyncCommand.java:87)
       at io.lettuce.core.internal.Futures.awaitOrCancel(Futures.java:244)
       at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:74)
       at org.springframework.data.redis.connection.lettuce.LettuceConnection.await(LettuceConnection.java:1084)
       ... 26 common frames omitted
aused by: java.lang.InterruptedException: null
       at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
       at java.util.concurrent.CompletableFuture.get(Unknown Source)
       at io.lettuce.core.protocol.AsyncCommand.await(AsyncCommand.java:83)
       ... 29 common frames omitted
```

**Comment by 648540858** [comment]
改前端返回流地址，再启动就报redis错误 是什么意思
