### ISSUE TITLE
wvp在docker容器内运行后出现错误

### ISSUE THREAD

**Issue by duankeke** [648540858/wvp-GB28181-pro#108]
我的wvp和zlm服务在同一个容器里面，我的宿主机ip是192.168.10.62，以下我的sip配置，当我运行java -jar wvp-gb28181-2.0.0-20210608013406.jar --spring.config.location=application.ym时出现了以下错误

sip:
    ip: 192.168.10.62
    port: 5060
    domain: 4401020049
    id: 44010200492000000001
    password: admin123

2021-06-08 17:03:51.111 ERROR 383 --- [           main] com.genersoft.iot.vmp.gb28181.SipLayer   : ??SIP????: Cannot assign requested address (Bind failed)

2021-06-08 17:03:51.116  WARN 383 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'udpSipProvider' defined in class path resource [com/genersoft/iot/vmp/gb28181/SipLayer.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sip.SipProvider]: Factory method 'startUdpListener' threw exception; nested exception is javax.sip.InvalidArgumentException: java.net.BindException: Cannot assign requested address (Bind failed)

2021-06-08 17:03:51.234  INFO 383 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-0} closing ...
2021-06-08 17:03:51.236  INFO 383 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2021-06-08 17:03:51.301  INFO 383 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-06-08 17:03:51.305 ERROR 383 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'udpSipProvider' defined in class path resource [com/genersoft/iot/vmp/gb28181/SipLayer.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sip.SipProvider]: Factory method 'startUdpListener' threw exception; nested exception is javax.sip.InvalidArgumentException: java.net.BindException: Cannot assign requested address (Bind failed)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:483) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.5.RELEASE.jar!/:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.5.RELEASE.jar!/:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.5.RELEASE.jar!/:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405) ~[spring-boot-2.3.5.RELEASE.jar!/:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.5.RELEASE.jar!/:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.5.RELEASE.jar!/:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.5.RELEASE.jar!/:2.3.5.RELEASE]
	at com.genersoft.iot.vmp.VManageBootstrap.main(VManageBootstrap.java:18) ~[classes!/:2.0.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[wvp-gb28181-2.0.0-20210608013406.jar:2.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) ~[wvp-gb28181-2.0.0-20210608013406.jar:2.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[wvp-gb28181-2.0.0-20210608013406.jar:2.0.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[wvp-gb28181-2.0.0-20210608013406.jar:2.0.0]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sip.SipProvider]: Factory method 'startUdpListener' threw exception; nested exception is javax.sip.InvalidArgumentException: java.net.BindException: Cannot assign requested address (Bind failed)

**Comment by 648540858** [comment]
请更新代码测试，新版不需要明确设置网卡ip，旧版需要，你的错误在于你设置的不是docker内的网卡ip。更新代码，或者是设置你的sip.ip为docker内网卡的ip

**Comment by RaymanTao** [comment]
> 请更新代码测试，新版不需要明确设置网卡ip，旧版需要，你的错误在于你设置的不是docker内的网卡ip。更新代码，或者是设置你的sip.ip为docker内网卡的ip

这个我绑定无论是docker自带的网桥还是我自己创建的网桥ip都不行，情况是绑定docker自动创建的网桥ip提示跟一楼一样的错误，绑定自己创建的网桥ip监听不到设备的上线注册情况，
