### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by liushuaigithup** [648540858/wvp-GB28181-pro#1144]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 windows / ubuntu/ centos ... 
 - windows 
 - 3. 端口开放情况
 - 本地环境
 - 4. 是否是公网部署 
 - 否
 - 5. 是否使用https
 - 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试
 - 8. 代码更新时间
分支-wvp-28181-2.0（2023-10-27）
**描述错误**
描述下您遇到的问题
启动项目redis异常
**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
2023-11-03 14:08:41.247  WARN --- GB28181_SIP : using default tls security policy
2023-11-03 14:08:41.253  WARN --- GB28181_SIP : Using default keystore type pkcs12
2023-11-03 14:08:41.254  WARN --- GB28181_SIP : TLS server settings will be inactive - TLS key store will use JVM defaults keyStoreType=pkcs12 javax.net.ssl.keyStore=null javax.net.ssl.keyStorePassword=null
2023-11-03 14:08:41.254  INFO --- GB28181_SIP : javax.net.ssl.trustStorePassword is null, using the password passed through javax.net.ssl.keyStorePassword
2023-11-03 14:08:41.254  WARN --- GB28181_SIP : Using default truststore type pkcs12
2023-11-03 14:08:41.254  WARN --- GB28181_SIP : TLS trust settings will be inactive - TLS trust store will use JVM defaults. trustStoreType=pkcs12 javax.net.ssl.trustStore=null javax.net.ssl.trustStorePassword=null
2023-11-03 14:08:41.366  INFO --- SipLayer : [SIP SERVER] tcp://192.168.1.108:15060 启动成功
2023-11-03 14:08:41.371  INFO --- SipLayer : [SIP SERVER] udp://192.168.1.108:15060 启动成功
2023-11-03 14:08:41.408  INFO --- HikariDataSource : HikariPool-1 - Starting...
2023-11-03 14:08:41.636  INFO --- HikariDataSource : HikariPool-1 - Start completed.
2023-11-03 14:08:41.714  INFO --- ZLMRunner : [zlm] 等待默认zlm中...
2023-11-03 14:08:41.716  INFO --- MediaServerServiceImpl : [zlm] 缓存初始化 
2023-11-03 14:08:41.921  INFO --- MediaServerServiceImpl : [ZLM] 正在连接 : ADGKNQTX036adgjn -> 192.168.1.108:8089
2023-11-03 14:08:41.951  INFO --- MediaServerServiceImpl : [ZLM] 正在设置 ：ADGKNQTX036adgjn -> 192.168.1.108:8089
2023-11-03 14:08:41.953  INFO --- MediaServerServiceImpl : [ZLM] 设置成功 ADGKNQTX036adgjn -> 192.168.1.108:8089
2023-11-03 14:08:41.956  INFO --- valuationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-11-03 14:08:41.996 ERROR --- SpringApplication : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:774)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.genersoft.iot.vmp.VManageBootstrap.main(VManageBootstrap.java:35)
Caused by: java.lang.NullPointerException: null
	at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl.zlmServerOnline(MediaServerServiceImpl.java:437)
	at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl$$FastClassBySpringCGLIB$$4a85d07a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
	at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl$$EnhancerBySpringCGLIB$$f6949583.zlmServerOnline(<generated>)
	at com.genersoft.iot.vmp.media.zlm.ZLMRunner.connectZlmServer(ZLMRunner.java:129)
	at com.genersoft.iot.vmp.media.zlm.ZLMRunner.run(ZLMRunner.java:96)
	at com.genersoft.iot.vmp.media.zlm.ZLMRunner$$FastClassBySpringCGLIB$$61f3e605.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
	at com.genersoft.iot.vmp.media.zlm.ZLMRunner$$EnhancerBySpringCGLIB$$b9472504.run(<generated>)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
	... 5 common frames omitted

2023-11-03 14:08:42.155  INFO --- HikariDataSource : HikariPool-1 - Shutdown initiated...
2023-11-03 14:08:42.162  INFO --- HikariDataSource : HikariPool-1 - Shutdown completed.
2023-11-03 14:08:42.509 ERROR --- SystemInfoTimerTask : [获取系统信息失败] sleep interrupted
2023-11-03 14:08:43.419 ERROR --- eAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(javax.sip.RequestEvent)

java.lang.IllegalStateException: LettuceConnectionFactory was destroyed and cannot be used anymore
	at org.springframework.util.Assert.state(Assert.java:76)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.assertInitialized(LettuceConnectionFactory.java:1263)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:414)
	at org.springframework.data.redis.core.RedisConnectionUtils.fetchConnection(RedisConnectionUtils.java:193)
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:144)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:105)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:211)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:191)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:178)
	at com.genersoft.iot.vmp.utils.redis.RedisUtil.scan(RedisUtil.java:31)
	at com.genersoft.iot.vmp.gb28181.session.VideoStreamSessionManager.getSsrcTransaction(VideoStreamSessionManager.java:71)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageRequestProcessor.process(MessageRequestProcessor.java:74)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(SIPProcessorObserver.java:83)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2023-11-03 14:08:43.852 ERROR --- eAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(javax.sip.RequestEvent)

java.lang.IllegalStateException: LettuceConnectionFactory was destroyed and cannot be used anymore
	at org.springframework.util.Assert.state(Assert.java:76)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.assertInitialized(LettuceConnectionFactory.java:1263)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:414)
	at org.springframework.data.redis.core.RedisConnectionUtils.fetchConnection(RedisConnectionUtils.java:193)
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:144)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:105)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:211)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:191)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:178)
	at com.genersoft.iot.vmp.utils.redis.RedisUtil.scan(RedisUtil.java:31)
	at com.genersoft.iot.vmp.gb28181.session.VideoStreamSessionManager.getSsrcTransaction(VideoStreamSessionManager.java:71)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageRequestProcessor.process(MessageRequestProcessor.java:74)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(SIPProcessorObserver.java:83)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2023-11-03 14:08:44.863 ERROR --- eAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(javax.sip.RequestEvent)

java.lang.IllegalStateException: LettuceConnectionFactory was destroyed and cannot be used anymore
	at org.springframework.util.Assert.state(Assert.java:76)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.assertInitialized(LettuceConnectionFactory.java:1263)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:414)
	at org.springframework.data.redis.core.RedisConnectionUtils.fetchConnection(RedisConnectionUtils.java:193)
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:144)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:105)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:211)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:191)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:178)
	at com.genersoft.iot.vmp.utils.redis.RedisUtil.scan(RedisUtil.java:31)
	at com.genersoft.iot.vmp.gb28181.session.VideoStreamSessionManager.getSsrcTransaction(VideoStreamSessionManager.java:71)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageRequestProcessor.process(MessageRequestProcessor.java:74)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(SIPProcessorObserver.java:83)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

与目标 VM 断开连接, 地址为: ''127.0.0.1:54125'，传输: '套接字''
```
进程已结束，退出代码为 -1

日志内容放这里， 文件的话请直接上传
```

**Comment by liushuaigithup** [comment]
1：reidis清理过和重启过

**Comment by liushuaigithup** [comment]
spring:
  # 设置接口超时时间
  mvc:
    async:
      request-timeout: 20000
  thymeleaf:
    cache: false
  # [可选]上传文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # REDIS数据库配置
  redis:
    # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
    host: 127.0.0.1
    # [必须修改] 端口号
    port: 6379
    # [可选] 数据库 DB
    database: 7
    # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
    password:
    # [可选] 超时时间
    timeout: 10000
    # mysql数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      connection-timeout: 20000             # 是客户端等待连接池连接的最大毫秒数
      initialSize: 10                       # 连接池初始化连接数
      maximum-pool-size: 200                # 连接池最大连接数
      minimum-idle: 5                       # 连接池最小空闲连接数
      idle-timeout: 300000                  # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
      max-lifetime: 1200000                 # 是池中连接关闭后的最长生命周期（以毫秒为单位)
#[可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
  port: 8080
  # [可选] HTTPS配置， 默认不开启
  ssl:
    # [可选] 是否开启HTTPS访问
    enabled: false
    # [可选] 证书文件路径，放置在resource/目录下即可，修改xxx为文件名
    key-store: classpath:test.monitor.89iot.cn.jks
    # [可选] 证书密码
    key-store-password: gpf64qmw
    # [可选] 证书类型， 默认为jks，根据实际修改
    key-store-type: JKS

# 作为28181服务器的配置
sip:
  # [必须修改] 本机的IP，对应你的网卡，监听什么ip就是使用什么网卡，
  # 如果要监听多张网卡，可以使用逗号分隔多个IP， 例如： 192.168.1.4,10.0.0.4
  # 如果不明白，就使用0.0.0.0，大部分情况都是可以的
  # 请不要使用127.0.0.1，任何包括localhost在内的域名都是不可以的。
  ip: 192.168.1.108
  # [可选] 28181服务监听的端口
  port: 15060
  # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
  # 后两位为行业编码，定义参照附录D.3
  # 3701020049标识山东济南历下区 信息行业接入
  # [可选]
  domain: 4101050000
  # [可选]
  id: 41010500002000000001
  # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
  password: 123456
  # 是否存储alarm信息
  alarm: true

#zlm 默认服务器配置
media:
  id: ADGKNQTX036adgjn
  # [必须修改] zlm服务器的内网IP
  ip: 192.168.1.108
  # [必须修改] zlm服务器的http.port
  http-port: 8089
  # [可选] 返回流地址时的ip，置空使用 media.ip
  stream-ip: 192.168.1.108
  # [可选] wvp在国标信令中使用的ip，此ip为摄像机可以访问到的ip， 置空使用 media.ip
  sdp-ip: 192.168.1.108
  # [可选] zlm服务器的hook所使用的IP, 默认使用sip.ip
  hook-ip: 192.168.1.108
  # [可选] zlm服务器的http.sslport, 置空使用zlm配置文件配置
  http-ssl-port: 8088
  # [可选] zlm服务器的hook.admin_params=secret
  secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
  # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
  rtp:
    # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
    enable: true
    # [可选] 在此范围内选择端口用于媒体流传输, 必须提前在zlm上配置该属性，不然自动配置此属性可能不成功
    port-range: 50000,50300 # 端口范围
    # [可选] 国标级联在此范围内选择端口发送媒体流,
    send-port-range: 50000,50300 # 端口范围
  # 录像辅助服务， 部署此服务可以实现zlm录像的管理与下载， 0 表示不使用
  record-assist-port: 18081
# [根据业务需求配置]
user-settings:
  # 点播/录像回放 等待超时时间,单位：毫秒
  play-timeout: 180000
  # [可选] 自动点播， 使用固定流地址进行播放时，如果未点播则自动进行点播, 需要rtp.enable=true
  auto-apply-play: true
  # 设备/通道状态变化时发送消息
  device-status-notify: true
  # 跨域配置，配置你访问前端页面的地址即可， 可以配置多个
  allowed-origins:
    - http://localhost:8080
    - http://127.0.0.1:8080
# [可选] 日志配置, 一般不需要改
logging:
  config: classpath:logback-spring-local.xml

这是我的配置文件

**Comment by 648540858** [comment]
配置文件贴一下

**Comment by MetSystem** [comment]
同样的问题，启动就会报错

**Comment by 648540858** [comment]
没有回复，我先关了
