### ISSUE TITLE
技术咨询，启动不了 Application run failed

### ISSUE THREAD

**Issue by ERAIT** [648540858/wvp-GB28181-pro#1166]
2023-11-20 15:26:09.666 ERROR --- SpringApplication : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:774)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.genersoft.iot.vmp.VManageBootstrap.main(VManageBootstrap.java:35)
Caused by: java.lang.NullPointerException: null
	at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl.zlmServerOnline(MediaServerServiceImpl.java:439)
	at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl$$FastClassBySpringCGLIB$$4a85d07a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
	at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl$$EnhancerBySpringCGLIB$$deff761c.zlmServerOnline(<generated>)
	at com.genersoft.iot.vmp.media.zlm.ZLMRunner.connectZlmServer(ZLMRunner.java:131)
	at com.genersoft.iot.vmp.media.zlm.ZLMRunner.run(ZLMRunner.java:96)
	at com.genersoft.iot.vmp.media.zlm.ZLMRunner$$FastClassBySpringCGLIB$$61f3e605.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
	at com.genersoft.iot.vmp.media.zlm.ZLMRunner$$EnhancerBySpringCGLIB$$a1b2059d.run(<generated>)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
	... 5 common frames omitted

**Comment by ERAIT** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/32009330/36832031-8a74-4767-8e60-bd10da96d935)

**Comment by ERAIT** [comment]
注册和连接看上去成功了，然后直接报错启动不了

**Comment by deng-h** [comment]
你好，我也遇到了同样的问题，请问解决了么
