### ISSUE TITLE
技术咨询-docker启动时的空指针异常

### ISSUE THREAD

**Issue by deng-h** [648540858/wvp-GB28181-pro#1248]
**环境信息:**

 - 1. 部署方式： wvp-pro docker
 - 2. 部署环境： centos7
 - 3. 端口开放情况：全开放
 - 4. 是否是公网部署 ：否
 - 5. 是否使用https：否
 - 6. 方便的话提供下使用的设备品牌或平台：英特尔NUC centos7
 - 7. 你做过哪些尝试：使用项目提供的docker-compose.yml
 - 8. 代码更新时间：最新

**内容描述:**
在启动应用程序的过程中,在执行 CommandLineRunner 时抛出了 NullPointerException
错误发生在 com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl 的 setZLMConfig 方法中,调用了一个 null 对象的方法导致了空指针异常
**截图**  

**抓包文件**
  
**日志**
```
 2024-01-10 16:15:42.231 [main]  INFO --- o.s.b.a.l.ConditionEvaluationReportLoggingListener: 136 
 
 Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
 2024-01-10 16:15:42.257 [main] ERROR --- org.springframework.boot.SpringApplication: 818 Application run failed
 
 java.lang.IllegalStateException: Failed to execute CommandLineRunner
   at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768)
   at org.springframework.boot.SpringApplication.lambda$callRunners$2(SpringApplication.java:749)
   at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
   at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
   at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
   at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
   at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
   at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
   at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
   at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
   at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:744)
   at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
   at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
   at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289)
   at com.genersoft.iot.vmp.VManageBootstrap.main(VManageBootstrap.java:35)
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
   at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
   at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
   at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
 Caused by: java.lang.NullPointerException: null
   at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl.setZLMConfig(MediaServerServiceImpl.java:596)
   at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl.zlmServerOnline(MediaServerServiceImpl.java:424)
   at com.genersoft.iot.vmp.media.zlm.ZLMRunner.connectZlmServer(ZLMRunner.java:129)
   at com.genersoft.iot.vmp.media.zlm.ZLMRunner.run(ZLMRunner.java:96)
   at com.genersoft.iot.vmp.media.zlm.ZLMRunner$$FastClassBySpringCGLIB$$61f3e605.invoke(<generated>)
   at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
   at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
   at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
   at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703)
   at com.genersoft.iot.vmp.media.zlm.ZLMRunner$$EnhancerBySpringCGLIB$$a272161d.run(<generated>)
   at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765)
   ... 22 common frames omitted
 
 2024-01-10 16:15:42.302 [main]  INFO --- com.zaxxer.hikari.HikariDataSource: 350 wvp - Shutdown initiated...
 2024-01-10 16:15:42.314 [main]  INFO --- com.zaxxer.hikari.HikariDataSource: 352 wvp - Shutdown completed.
 2024-01-10 16:15:43.314 [scheduled-task-pool-4] ERROR --- o.s.s.support.TaskUtils$LoggingErrorHandler: 95 Unexpected error occurred in scheduled task
 
 java.lang.IllegalStateException: LettuceConnectionFactory was destroyed and cannot be used anymore
   at org.springframework.util.Assert.state(Assert.java:76)
   at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.assertInitialized(LettuceConnectionFactory.java:1263)
   at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:414)
   at org.springframework.data.redis.core.RedisConnectionUtils.fetchConnection(RedisConnectionUtils.java:193)
   at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:144)
   at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:105)
   at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:211)
   at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:191)
   at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:97)
   at org.springframework.data.redis.core.DefaultListOperations.rightPush(DefaultListOperations.java:280)
   at com.genersoft.iot.vmp.storager.impl.RedisCatchStorageImpl.addNetInfo(RedisCatchStorageImpl.java:520)
   at com.genersoft.iot.vmp.conf.SystemInfoTimerTask.execute(SystemInfoTimerTask.java:34)
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
   at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
   at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
   at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by deng-h** [comment]
已调通

**Comment by colin354** [comment]
您好，我也遇到了相同的问题，请问是如何解决的？
![image](https://github.com/user-attachments/assets/8f57ba0b-4a32-498b-85df-8eb251f51bf0)
