### ISSUE TITLE
一个比较奇怪的问题，ZLM的端口被覆盖

### ISSUE THREAD

**Issue by gelald** [648540858/wvp-GB28181-pro#128]
我在application-dev.yml文件中的media.http-port属性中配置了zlm的端口，但是每次启动都被覆盖成了80端口。我是用docker部署的zlmediakit的，容器的80端口映射到宿主机的端口是11180，所以80端口自然是无法连接到zlm的。请问会有什么原因造成呢？

**Comment by gelald** [comment]
![Snipaste_2021-07-20_11-06-41](https://user-images.githubusercontent.com/37375083/126256331-cb5f42b8-bfcb-4aeb-9ce9-6875a7dd0891.png)

**Comment by gelald** [comment]
清除数据库media_server后不再有报错，能连接成功，但是显示的连接仍旧是80端口
![Uploading Snipaste_2021-07-20_11-21-16.png…]()

**Comment by gelald** [comment]
清除数据库media_server后不再有报错，能连接成功，但是显示的连接仍旧是80端口
![Snipaste_2021-07-20_11-21-16](https://user-images.githubusercontent.com/37375083/126256997-3fccb4d2-57bb-4524-8a35-61311ada74da.png)

**Comment by lolkt** [comment]
怎么解决？

**Comment by lolkt** [comment]
请问怎么解决的，清除数据库也没用。
`2021-07-22 11:38:57.277  INFO 22124 --- [           main] c.genersoft.iot.vmp.media.zlm.ZLMRunner  : 等待默认zlm接入...
2021-07-22 11:38:57.378 DEBUG 22124 --- [      Thread-22] c.g.iot.vmp.media.zlm.ZLMRESTfulUtils    : http://10.0.0.18:8080/index/api/getServerConfig
2021-07-22 11:38:57.378 DEBUG 22124 --- [      Thread-21] c.g.iot.vmp.media.zlm.ZLMRESTfulUtils    : http://10.0.0.18:80/index/api/getServerConfig
2021-07-22 11:38:57.389  INFO 22124 --- [           main] c.g.i.v.s.impl.VideoManagerStoragerImpl  : 更新所有设备离线
2021-07-22 11:38:57.442 ERROR 22124 --- [      Thread-21] c.genersoft.iot.vmp.media.zlm.ZLMRunner  : [ rapAJN3x2EMfyXae ]-[ 10.0.0.18:80 ]主动连接失败失败, 2s后重试
2021-07-22 11:38:57.456  INFO 22124 --- [      Thread-22] c.g.i.v.s.impl.MediaServerServiceImpl    : [ rapAJN3x2EMfyXae ]-[ 10.0.0.18:80 ]已连接
2021-07-22 11:38:57.464  INFO 22124 --- [      Thread-22] c.g.i.v.s.impl.MediaServerServiceImpl    : [ rapAJN3x2EMfyXae ]-[ 10.0.0.18:80 ]设置zlm
2021-07-22 11:38:57.466 DEBUG 22124 --- [      Thread-22] c.g.iot.vmp.media.zlm.ZLMRESTfulUtils    : http://10.0.0.18:80/index/api/setServerConfig
Exception in thread "Thread-22" java.lang.NullPointerException
	at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl.setZLMConfig(MediaServerServiceImpl.java:336)
	at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl.handLeZLMServerConfig(MediaServerServiceImpl.java:189)
	at com.genersoft.iot.vmp.media.zlm.ZLMRunner.lambda$run$1(ZLMRunner.java:83)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by gelald** [comment]
嗯，我还以为只有我一个人是这样，我用最新的代码，无论怎么配置application-dev.yml文件中的zlm端口，无论怎么清除数据库和缓存，都是连的80端口，现在只能用着同事之前用的旧版本的来调试

**Comment by gelald** [comment]
嗯，我还以为只有我一个人是这样，我用最新的代码，无论怎么配置application-dev.yml文件中的zlm端口，无论怎么清除数据库和缓存，都是连的80端口，现在只能用着同事之前用的旧版本的来调试

**Comment by 648540858** [comment]
我测试下

**Comment by gelald** [comment]
怎么样，您这边有同样的问题吗

**Comment by lolkt** [comment]
使用场景是idea直接运行，使用默认sqlite数据库，查询media_server 表为空

**Comment by zfj0952** [comment]
同样docker部署，端口修改为不是原来默认的80就出现这个问题

**Comment by gelald** [comment]
> 同样docker部署，端口修改为不是原来默认的80，application-dev里没有配置media.id就出现这个问题
> 
> 删除media_server表的数据，获取zlm的id配置在application-dev的media.id重启可以成功

这种做法可以解决问题

**Comment by duankeke** [comment]
我也有这个问题，就是我的media.id和zlm的ZLM的general.mediaServerId，是一样的，但是java启动程序的时候，查数据库总是是另一个id。导致连接不上zlm，
打印信息： 
executed. 1.522084 millis. SELECT * FROM media_server WHERE id='O5e7OSQWZuuNdwHU'
 [未注册的zlm] 拒接接入：O5e7OSQWZuuNdwHU来自192.168.10.217：6080
请检查ZLM的<general.mediaServerId>配置是否与WVP的<media.id>一致

这个不会是随机生成的吧：O5e7OSQWZuuNdwHU，代码中也没看到写死

**Comment by gelald** [comment]
抱歉，我接近1年时间没有接触这个项目了，没什么印象了
