### ISSUE TITLE
BUG xml 解析报错

### ISSUE THREAD

**Issue by iwanlebron** [648540858/wvp-GB28181-pro#1320]
2024-02-21 18:06:38.867 [wvp-7] WARN  c.g.i.v.g.t.e.request.SIPRequestProcessorParent:206 - [xml解析异常]： 原文如下： 
<?xml version="1.0" encoding="GB2312"?>
<Response>
<CmdType>Catalog</CmdType>
<SN>317343</SN>
<DeviceID>61010500002000000001</DeviceID>
<SumNum>2</SumNum>
<DeviceList Num="1">
<Item>
<DeviceID>61010500009994655540</DeviceID>
<Name>001030010-client-b371fd2650f740d8b5b25fb3709b2765-kkkkkkkk-7-1</Name>
</Item>
</Item>
</DeviceList>
</Response>

2024-02-21 18:06:38.867 [wvp-7] WARN  c.g.i.v.g.t.e.request.SIPRequestProcessorParent:207 - [xml解析异常]： 原文如下： 尝试兼容性处理
2024-02-21 18:06:38.868 [wvp-7] WARN  c.g.i.v.g.t.e.r.i.message.MessageRequestProcessor:114 - 解析XML消息内容异常
org.dom4j.DocumentException: Error on line 1 of document  : 在文档的元素内容中找到无效的 XML 字符 (Unicode: 0x0)。
        at org.dom4j.io.SAXReader.read(SAXReader.java:511)
        at org.dom4j.io.SAXReader.read(SAXReader.java:392)
        at com.genersoft.iot.vmp.gb28181.transmit.event.request.SIPRequestProcessorParent.getRootElement(SIPRequestProcessorParent.java:218)
        at com.genersoft.iot.vmp.gb28181.transmit.event.request.SIPRequestProcessorParent.getRootElement(SIPRequestProcessorParent.java:166)
        at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageRequestProcessor.process(MessageRequestProcessor.java:107)
        at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(SIPProcessorObserver.java:83)
        at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.xml.sax.SAXParseException: 在文档的元素内容中找到无效的 XML 字符 (Unicode: 0x0)。
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2925)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:113)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:507)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:867)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:796)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:142)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:644)
        at org.dom4j.io.SAXReader.read(SAXReader.java:494)
        ... 15 common frames omitted
2024-02-21 18:06:38.955 [wvp-8] INFO  c.g.i.v.g.t.e.r.i.m.n.c.KeepaliveNotifyMessageHandler:64 - [收到心跳] device: 61010500002000000001, callId: 224ea132fceb2cdf0142457f8baa772a@192.168.15.97
2024-02-21 18:06:47.262 [wvp-6] WARN  c.g.i.v.g.t.e.r.i.message.MessageRequestProcessor:97 - [设备未找到 ]deviceId: 41010500002000000001, callId: 7f4cc02c5d3c7c48d0ed12777982b05d@192.168.111.142

**Comment by iwanlebron** [comment]
名字中不能含有 - 吗

**Comment by iwanlebron** [comment]
xml 中多了一个 </Item>

**Comment by iwanlebron** [comment]
<img width="872" alt="image" src="https://github.com/648540858/wvp-GB28181-pro/assets/105045937/bde47ce2-b56c-4da4-b038-7e82328e39dc">
都是utf8mb4  有乱码
