### ISSUE TITLE
BUG 下级wvp向上级公网wvp注册一直离线

### ISSUE THREAD

**Issue by iwanlebron** [648540858/wvp-GB28181-pro#1388]
**环境信息:**

 - 1. 部署方式 wvp-pro wvp-prp + zlm都是编译部署
 - 2. 部署环境 centos 
 - 3. 端口开放情况 开放
 - 4. 是否是公网部署  上级是公网，下级为内网
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试 更新到最新代码
 - 8. 代码更新时间 最新

**描述错误**
下级wvp向上级注册一直离线

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  

**抓包文件**
  
**日志**
```
2024-03-25 18:59:19.331 [http-nio-11592-exec-1]  WARN --- GB28181_SIP: 451 Failed to connect /121.36.107.177:11593 but trying the advertised port=11593 if it's different than the port we just failed on

2024-03-25 18:59:19.331 [http-nio-11592-exec-1] ERROR --- GB28181_SIP: 441 Error is



java.io.IOException: Could not connect to /121.36.107.177:11593

        at gov.nist.javax.sip.stack.IOHandler.sendBytes(IOHandler.java:391)

        at gov.nist.javax.sip.stack.TCPMessageChannel.sendMessage(TCPMessageChannel.java:350)

        at gov.nist.javax.sip.stack.MessageChannel.sendMessage(MessageChannel.java:259)

        at gov.nist.javax.sip.SipProviderImpl.sendRequest(SipProviderImpl.java:746)

        at com.genersoft.iot.vmp.gb28181.transmit.SIPSender.transmitRequest(SIPSender.java:89)

        at com.genersoft.iot.vmp.gb28181.transmit.cmd.impl.SIPCommanderFroPlatform.register(SIPCommanderFroPlatform.java:154)

        at com.genersoft.iot.vmp.gb28181.transmit.cmd.impl.SIPCommanderFroPlatform.register(SIPCommanderFroPlatform.java:96)

        at com.genersoft.iot.vmp.service.impl.PlatformServiceImpl.update(PlatformServiceImpl.java:210)

        at com.genersoft.iot.vmp.service.impl.PlatformServiceImpl$$FastClassBySpringCGLIB$$110c36b6.invoke(<generated>)

        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)

        at com.baomidou.dynamic.datasource.aop.DynamicDataSourceAnnotationInterceptor.invoke(DynamicDataSourceAnnotationInterceptor.java:50)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)

        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)

        at com.genersoft.iot.vmp.service.impl.PlatformServiceImpl$$EnhancerBySpringCGLIB$$5a90c7f.update(<generated>)

        at com.genersoft.iot.vmp.vmanager.gb28181.platform.PlatformController.savePlatform(PlatformController.java:212)

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.base/java.lang.reflect.Method.invoke(Method.java:568)

        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)

        at org.spri ngframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)

        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)

        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)

        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)

        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)

        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)

        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)

        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)

        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)

        at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)

        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)

        at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)

        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)

        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:111)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)

```

**Comment by iwanlebron** [comment]
可以telnet 通 11593端口

**Comment by 648540858** [comment]
信令模式使用udp试试

**Comment by iwanlebron** [comment]
也不行

**Comment by BradyXs** [comment]
自己测试下网络连通情况就行，这个不用提ISSUES

**Comment by iwanlebron** [comment]
好的 辛苦看看这个 https://github.com/648540858/wvp-GB28181-pro/issues/1470

**Comment by iwanlebron** [comment]
![image](https://github.com/648540858/wvp-GB28181-pro/assets/105045937/8eed7412-5610-4f26-8f25-aa97b28a3913)
