### ISSUE TITLE
上级国标平台无法调取经OBS-RTMP推流视频

### ISSUE THREAD

**Issue by hnnaheziqiang** [648540858/wvp-GB28181-pro#1536]
**环境信息:**

 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 ubuntu
 - 3. 端口开放情况 全开
 - 4. 是否是公网部署 否
 - 5. 是否使用https 否
 - 6. 代码更新时间 v2.7.2

**内容描述:**
源视频通过OBS推流至MVP平台，mvp平台推流列表中可正常播放，经国标级联到上级平台后无法预览。另外mvp平台上通过GB28181接入的海康摄像头，经过级联到同一上级平台可正常预览视频。

**日志**
```


2024-07-18 23:21:13.254 [wvp-3]  INFO --- c.g.iot.vmp.media.zlm.ZLMMediaServerStatusManger: 110 [ZLM-HOOK事件-心跳] ID：zlm

2024-07-18 23:21:21.257 [wvp-4]  INFO --- c.g.i.v.g.t.e.request.impl.InviteRequestProcessor: 186 [INVITE] requesterId: 34020000002000000001, callId: 536870939@192.168.168.165:0, 来自：/192.168.168.165：5060

2024-07-18 23:21:21.280 [wvp-4] ERROR --- o.s.a.i.SimpleAsyncUncaughtExceptionHandler: 39 Unexpected exception occurred invoking async method: public void com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(javax.sip.RequestEvent)

java.lang.NullPointerException: null
	at 
com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.InviteRequestProcessor.sendPushStream(InviteRequestProcessor.java:691)
	at 
com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.InviteRequestProcessor.process(InviteRequestProcessor.java:604)
	at 
com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(SIPProcessorObserver.java:83)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>)
	at 
org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at 
org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
	at 
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)



```

**Comment by 648540858** [comment]
提供下抓包和完整的日志文件
