### ISSUE TITLE
BUG 语音对讲里的对讲功能代码报错

### ISSUE THREAD

**Issue by zhouchenxing** [648540858/wvp-GB28181-pro#1692]
**环境信息:**
 - 1. 部署方式：wvp-pro 在win10系统 zlm在win10系统 + 编译：wvp-pro+ zlm都是在win10系统
 - 2. 部署环境 ：windows
 - 3. 端口开放情况：都开放
 - 4. 是否是公网部署：否
 - 5. 是否使用https：否
 - 6. 接入设备/平台品牌：海康威视
 - 7. 你做过哪些尝试：代码已经更新到最新版本
 - 8. 代码更新时间：2024年11月14日
 - 9. 是否是4G设备接入：未知
**描述错误**
描述下您遇到的问题
语音对讲里的对讲功能代码报错，喊话功能正常并在摄像头端能听到语音。其中我的wvp代码，流媒体，摄像头都在内网的同一个网段下，播放功能正常，喊话功能正常，就是对讲功能报错。

**如何复现**
有明确复现步骤的问题会很容易被解决
1.选择对讲，开始对讲
2.或者直接执行命令。
ffmpeg -re -i nothing2.flac -acodec pcm_alaw -ar 8000 -ac 1 -f rtsp "rtsp://127.0.0.1/talk/34020000001320000244_34020000001320000244?sign=41db35390ddad33f83944f44b8b75ded"
pause
**截图**  
![image](https://github.com/user-attachments/assets/0079babd-506e-4969-b8dc-7c74ea439ec5)
![image](https://github.com/user-attachments/assets/9ea125b2-4de1-4e97-9207-5ec39566fa79)
**抓包文件**
  无
**日志**
2024-11-14 15:06:48.190 [http-nio-18080-exec-3]  INFO --- c.g.iot.vmp.gb28181.service.impl.PlayServiceImpl: 1209 [语音喊话] device： 34020000001320000244, channel: 34020000001320000244
2024-11-14 15:06:48.654 [http-nio-18080-exec-8]  INFO --- c.genersoft.iot.vmp.media.zlm.ZLMHttpHookListener: 100 [ZLM HOOK]推流鉴权：bvmp-zlm-server->OnPublishHookParam{id='466-1896', app='talk', stream='34020000001320000244_34020000001320000244', ip='192.168.31.13', params='app=talk&stream=34020000001320000244_34020000001320000244&type=push&sign=41db35390ddad33f83944f44b8b75ded&session=466-1896', port=55525, schema='rtc', vhost='__defaultVhost__'}
2024-11-14 15:06:48.660 [http-nio-18080-exec-8]  INFO --- c.genersoft.iot.vmp.media.zlm.ZLMHttpHookListener: 112 [ZLM HOOK]推流鉴权 响应：bvmp-zlm-server->OnPublishHookParam{id='466-1896', app='talk', stream='34020000001320000244_34020000001320000244', ip='192.168.31.13', params='app=talk&stream=34020000001320000244_34020000001320000244&type=push&sign=41db35390ddad33f83944f44b8b75ded&session=466-1896', port=55525, schema='rtc', vhost='__defaultVhost__'}->>>>HookResultForOnPublish{enable_audio=true, enable_mp4=false, mp4_max_second=0, mp4_save_path='null', stream_replace='null', modify_stamp='null'}
2024-11-14 15:06:48.950 [http-nio-18080-exec-2]  INFO --- c.genersoft.iot.vmp.media.zlm.ZLMHttpHookListener: 148 [ZLM HOOK] 流注册, bvmp-zlm-server->rtsp->talk/34020000001320000244_34020000001320000244
2024-11-14 15:06:48.950 [wvp-9]  INFO --- c.g.i.v.media.service.impl.MediaServerServiceImpl: 92 流变化：注册 app->talk, stream->34020000001320000244_34020000001320000244
2024-11-14 15:06:48.953 [wvp-8]  INFO --- c.g.i.v.s.service.impl.StreamPushServiceImpl: 196 [添加推流] app: talk, stream: 34020000001320000244_34020000001320000244, 国标编号: null
2024-11-14 15:06:48.966 [wvp-8]  INFO --- c.g.iot.vmp.storager.impl.RedisCatchStorageImpl: 121 [redis 流变化事件] 发送 WVP_MSG_STREAM_CHANGE_PUSH: {"serverId":"000000","app":"talk","stream":"34020000001320000244_34020000001320000244","register":true,"mediaServerId":"bvmp-zlm-server"}
2024-11-14 15:06:48.966 [wvp-5]  INFO --- c.g.iot.vmp.gb28181.service.impl.PlayServiceImpl: 1454 [语音对讲] device： 34020000001320000244, channel: 34020000001320000244
2024-11-14 15:06:48.970 [wvp-5] ERROR --- o.s.a.i.SimpleAsyncUncaughtExceptionHandler: 39 Unexpected exception occurred invoking async method: public void com.genersoft.iot.vmp.gb28181.service.impl.PlayServiceImpl.onApplicationEvent(com.genersoft.iot.vmp.media.event.media.MediaArrivalEvent)

java.lang.NullPointerException: null
	at com.genersoft.iot.vmp.service.impl.SendRtpServerServiceImpl.createSendRtpInfo(SendRtpServerServiceImpl.java:52)
	at com.genersoft.iot.vmp.gb28181.service.impl.PlayServiceImpl.talk(PlayServiceImpl.java:485)
	at com.genersoft.iot.vmp.gb28181.service.impl.PlayServiceImpl.talkCmd(PlayServiceImpl.java:1485)
	at com.genersoft.iot.vmp.gb28181.service.impl.PlayServiceImpl.onApplicationEvent(PlayServiceImpl.java:165)
	at com.genersoft.iot.vmp.gb28181.service.impl.PlayServiceImpl$$FastClassBySpringCGLIB$$6af2573a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	at com.baomidou.dynamic.datasource.aop.DynamicDataSourceAnnotationInterceptor.invoke(DynamicDataSourceAnnotationInterceptor.java:50)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2024-11-14 15:06:51.165 [http-nio-18080-exec-1]  INFO --- c.genersoft.iot.vmp.media.zlm.ZLMHttpHookListener: 164 [ZLM HOOK] 流注销, bvmp-zlm-server->rtsp->talk/34020000001320000244_34020000001320000244
2024-11-14 15:06:51.166 [wvp-15]  INFO --- c.g.i.v.media.service.impl.MediaServerServiceImpl: 106 流变化：注销, app->talk, stream->34020000001320000244_34020000001320000244
2024-11-14 15:06:51.168 [wvp-2]  INFO --- c.g.iot.vmp.storager.impl.RedisCatchStorageImpl: 121 [redis 流变化事件] 发送 WVP_MSG_STREAM_CHANGE_PUSH: {"serverId":"000000","app":"talk","stream":"34020000001320000244_34020000001320000244","register":false,"mediaServerId":"bvmp-zlm-server"}
2024-11-14 15:06:51.172 [wvp-2]  INFO --- c.g.i.v.s.service.impl.StreamPushServiceImpl: 221 [删除推流] app: talk, stream: 34020000001320000244_34020000001320000244, 
2024-11-14 15:06:51.172 [wvp-3]  INFO --- c.g.iot.vmp.gb28181.service.impl.PlayServiceImpl: 1507 [语音对讲] 停止， 34020000001320000244/34020000001320000244
2024-11-14 15:06:51.173 [wvp-2]  INFO --- c.g.i.v.s.service.impl.StreamPushServiceImpl: 261 [主动停止推流] id: 149, app: talk, stream: 34020000001320000244_34020000001320000244, 
2024-11-14 15:06:51.173 [wvp-3]  INFO --- c.g.iot.vmp.gb28181.service.impl.PlayServiceImpl: 1510 [语音对讲] 停止失败， 未找到发送信息，可能已经停止
2024-11-14 15:06:51.178 [wvp-2]  INFO --- c.g.iot.vmp.media.zlm.ZLMMediaNodeServerService: 140 停止发流结果: can not find the stream, 参数：{"app":"talk","vhost":"__defaultVhost__","stream":"34020000001320000244_34020000001320000244"}
```
日志内容放这里， 文件的话请直接上传
```

**Comment by 648540858** [comment]
修复了
