### ISSUE TITLE
技术咨询 SDP解析错误，缺少Missing host name

### ISSUE THREAD

**Issue by yhl-186** [648540858/wvp-GB28181-pro#1703]
**环境信息:**

 - 1. 部署方式  zlm(docker) + 编译wvp-pro部署/
 - 2. 部署环境 wvp-pro是windows / zlm(docker)是ubuntu/ 
 - 3. 端口开放情况 全部开放
 - 4. 是否是公网部署 都是在局域网内
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试
 - 8. 代码更新时间（旧版本请更新最新版本代码测试）

**内容描述:**

**截图**  
![屏幕截图 2024-11-25 100249](https://github.com/user-attachments/assets/c559ab7d-a2cc-47ea-a066-282768931278)

**抓包文件**
  
**日志**
```

2024-11-25 09:41:02.750 [http-nio-18080-exec-4]  INFO --- c.g.iot.vmp.gb28181.transmit.cmd.impl.SIPCommander: 336 构建SDP消息: v=0
o=34020000001320000001 0 0 IN IP4 192.168.10.64:8116
s=Play
c=IN IP4 192.168.10.64:8116
t=0 0
m=video 20442 RTP/AVP 96 97 98 99
a=recvonly
a=rtpmap:96 PS/90000
a=rtpmap:98 H264/90000
a=rtpmap:97 MPEG4/90000
a=rtpmap:99 H265/90000
a=stream:0
y=0200003312

2024-11-25 09:41:02.780 [wvp-7]  INFO --- com.genersoft.iot.vmp.gb28181.utils.SipUtils: 199 解析SDP消息: v=0
o=34020000001320000001 3539 3539 IN IP4 
s=Play
c=IN IP4 
t=0 0
m=video 15060 RTP/AVP 96
a=sendonly
a=rtpmap:96 PS/90000
a=filesize:0
y=0200003312

2024-11-25 09:41:02.794 [wvp-7] ERROR --- com.genersoft.iot.vmp.gb28181.utils.SipUtils: 224 解析SDP消息失败: v=0
java.text.ParseException: : Missing host name
	at gov.nist.core.HostNameParser.host(HostNameParser.java:194)
	at gov.nist.javax.sdp.parser.OriginFieldParser.originField(OriginFieldParser.java:97)
	at gov.nist.javax.sdp.parser.OriginFieldParser.parse(OriginFieldParser.java:108)
	at gov.nist.javax.sdp.parser.SDPAnnounceParser.parse(SDPAnnounceParser.java:113)
	at javax.sdp.SdpFactory.createSessionDescription(SdpFactory.java:129)
	at com.genersoft.iot.vmp.gb28181.utils.SipUtils.parseSDP(SipUtils.java:222)
	at com.genersoft.iot.vmp.gb28181.transmit.event.response.impl.InviteResponseProcessor.process(InviteResponseProcessor.java:76)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processResponse(SIPProcessorObserver.java:111)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.text.ParseException: o=34020000001320000001 3539 3539 IN IP4
	at gov.nist.javax.sdp.parser.OriginFieldParser.originField(OriginFieldParser.java:103)
	at gov.nist.javax.sdp.parser.OriginFieldParser.parse(OriginFieldParser.java:108)
	at gov.nist.javax.sdp.parser.SDPAnnounceParser.parse(SDPAnnounceParser.java:113)
	at javax.sdp.SdpFactory.createSessionDescription(SdpFactory.java:129)
	at com.genersoft.iot.vmp.gb28181.utils.SipUtils.parseSDP(SipUtils.java:222)
	at com.genersoft.iot.vmp.gb28181.transmit.event.response.impl.InviteResponseProcessor.process(InviteResponseProcessor.java:76)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processResponse(SIPProcessorObserver.java:111)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
o=34020000001320000001 3539 3539 IN IP4
s=Play
c=IN IP4
t=0 0
m=video 15060 RTP/AVP 96
a=sendonly
a=rtpmap:96 PS/90000
a=filesize:0

```

**Comment by 648540858** [comment]
缺少了收流地址
```
c=IN IP4 
```
后面应该有个地址
