### ISSUE TITLE
BUG,处理心跳有问题

### ISSUE THREAD

**Issue by 1322630531** [648540858/wvp-GB28181-pro#1715]
**环境信息:**

 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 centos

**描述错误**
10月30号提交的增强心跳消息并发处理 648540858 2024/10/30 15:19
好像有问题。项目启动不播放视频的情况下能正常执行executeTaskQueue方法，当任意播放视频之后executeTaskQueue就不会执行了

**如何复现**
播放任意视频

[wvp-pro.log](https://github.com/user-attachments/files/18106916/wvp-pro.log)
抓包那边查看之后的效果心跳包在项目启动后没有播放视频的情况下心跳包是有来有回的，当播放视频后心跳包就没有回复了

**Comment by 1322630531** [comment]
![Snipaste_2024-12-12_14-51-58](https://github.com/user-attachments/assets/eceba4af-0407-4097-9fb4-5952f3b92027)

**Comment by 1322630531** [comment]
![Uploading Snipaste_2024-12-12_14-59-10.png…]()

**Comment by 1322630531** [comment]
![Snipaste_2024-12-12_14-51-58](https://github.com/user-attachments/assets/78b7080c-9cbf-46a9-8335-b91f500c51b3)
![Snipaste_2024-12-12_14-59-10](https://github.com/user-attachments/assets/50995d13-d5e4-4fe8-8571-5087ce75553a)

**Comment by 1322630531** [comment]
初步怀疑可能和Runtime.getRuntime().availableProcessors()有关，这台服务器的Runtime.getRuntime().availableProcessors()只有1，而在ScheduleConfig中是按这个来创建线程的

**Comment by 1322630531** [comment]
而我通过nproc执行出来的是32

**Comment by 648540858** [comment]
我调整了线程池的配置， 你试试

**Comment by 648540858** [comment]
> 最新代码运行报错：
> 
> ```
> 2024-12-15 23:06:12.656 [dynamicTask-68] ERROR --- o.s.s.support.TaskUtils$LoggingErrorHandler: 95 Unexpected error occurred in scheduled task
> 
> java.lang.IllegalArgumentException: Bad code -2
>         at gov.nist.javax.sip.message.SIPRequest.createResponse(SIPRequest.java:680)
>         at gov.nist.javax.sip.message.SIPRequest.createResponse(SIPRequest.java:650)
>         at gov.nist.javax.sip.message.MessageFactoryImpl.createResponse(MessageFactoryImpl.java:504)
>         at com.genersoft.iot.vmp.gb28181.transmit.event.request.SIPRequestProcessorParent.responseAck(SIPRequestProcessorParent.java:88)
>         at com.genersoft.iot.vmp.gb28181.transmit.event.request.SIPRequestProcessorParent.responseAck(SIPRequestProcessorParent.java:80)
>         at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.InviteRequestProcessor.lambda$process$1(InviteRequestProcessor.java:167)
>         at com.genersoft.iot.vmp.gb28181.service.impl.PlayServiceImpl.lambda$play$4(PlayServiceImpl.java:403)
>         at com.genersoft.iot.vmp.service.impl.RtpServerServiceImpl.lambda$openRTPServer$0(RtpServerServiceImpl.java:134)
>         at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
>         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
>         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
>         at java.base/java.lang.Thread.run(Thread.java:833)
> 
> 2024-12-15 23:06:12.656 [dynamicTask-295]  INFO --- com.genersoft.iot.vmp.media.zlm.ZLMServerFactory: 101 关闭RTP Server {"code":0,"hit":0}
> 2024-12-15 23:06:12.656 [async-114] ERROR --- c.g.i.v.g.service.impl.GbChannelPlayServiceImpl: 122 [点播失败] IPC000415(44012628484328000415)
> 
> java.lang.IllegalArgumentException: Bad code -3
>         at gov.nist.javax.sip.message.SIPRequest.createResponse(SIPRequest.java:680)
>         at gov.nist.javax.sip.message.SIPRequest.createResponse(SIPRequest.java:650)
>         at gov.nist.javax.sip.message.MessageFactoryImpl.createResponse(MessageFactoryImpl.java:504)
>         at com.genersoft.iot.vmp.gb28181.transmit.event.request.SIPRequestProcessorParent.responseAck(SIPRequestProcessorParent.java:88)
>         at com.genersoft.iot.vmp.gb28181.transmit.event.request.SIPRequestProcessorParent.responseAck(SIPRequestProcessorParent.java:80)
>         at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.InviteRequestProcessor.lambda$process$1(InviteRequestProcessor.java:167)
>         at com.genersoft.iot.vmp.gb28181.service.impl.PlayServiceImpl.play(PlayServiceImpl.java:421)
>         at com.genersoft.iot.vmp.gb28181.service.impl.PlayServiceImpl.play(PlayServiceImpl.java:1662)
>         at com.genersoft.iot.vmp.gb28181.service.impl.PlayServiceImpl$$FastClassBySpringCGLIB$$6af2573a.invoke(<generated>)
>         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
>         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
>         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
>         at com.baomidou.dynamic.datasource.aop.DynamicDataSourceAnnotationInterceptor.invoke(DynamicDataSourceAnnotationInterceptor.java:50)
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
>         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
>         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
>         at com.genersoft.iot.vmp.gb28181.service.impl.PlayServiceImpl$$EnhancerBySpringCGLIB$$6eaccea3.play(<generated>)
>         at com.genersoft.iot.vmp.gb28181.service.impl.GbChannelPlayServiceImpl.playGbDeviceChannel(GbChannelPlayServiceImpl.java:118)
>         at com.genersoft.iot.vmp.gb28181.service.impl.GbChannelPlayServiceImpl.play(GbChannelPlayServiceImpl.java:95)
>         at com.genersoft.iot.vmp.gb28181.service.impl.GbChannelPlayServiceImpl.start(GbChannelPlayServiceImpl.java:42)
>         at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.InviteRequestProcessor.process(InviteRequestProcessor.java:164)
>         at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(SIPProcessorObserver.java:80)
>         at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>)
>         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
>         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
>         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
>         at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
>         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
>         at java.base/java.lang.Thread.run(Thread.java:833)
> ```
> 
> > 我调整了线程池的配置， 你试试

麻烦提供下完整的日志,

**Comment by 1322630531** [comment]
我这边好像能正常运行了

**Comment by 648540858** [comment]
> 我这边好像能正常运行了

好的, 你再观看下,再有问题再报给我

**Comment by 648540858** [comment]
在更新下，昨天修复了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月17日(周二) 中午11:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [648540858/wvp-GB28181-pro] BUG,处理心跳有问题 (Issue #1715)




   
最新代码运行报错：
 2024-12-15 23:06:12.656 [dynamicTask-68] ERROR --- o.s.s.support.TaskUtils$LoggingErrorHandler: 95 Unexpected error occurred in scheduled task java.lang.IllegalArgumentException: Bad code -2         at gov.nist.javax.sip.message.SIPRequest.createResponse(SIPRequest.java:680)         at gov.nist.javax.sip.message.SIPRequest.createResponse(SIPRequest.java:650)         at gov.nist.javax.sip.message.MessageFactoryImpl.createResponse(MessageFactoryImpl.java:504)         at com.genersoft.iot.vmp.gb28181.transmit.event.request.SIPRequestProcessorParent.responseAck(SIPRequestProcessorParent.java:88)         at com.genersoft.iot.vmp.gb28181.transmit.event.request.SIPRequestProcessorParent.responseAck(SIPRequestProcessorParent.java:80)         at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.InviteRequestProcessor.lambda$process$1(InviteRequestProcessor.java:167)         at com.genersoft.iot.vmp.gb28181.service.impl.PlayServiceImpl.lambda$play$4(PlayServiceImpl.java:403)         at com.genersoft.iot.vmp.service.impl.RtpServerServiceImpl.lambda$openRTPServer$0(RtpServerServiceImpl.java:134)         at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)         at java.base/java.lang.Thread.run(Thread.java:833) 2024-12-15 23:06:12.656 [dynamicTask-295]  INFO --- com.genersoft.iot.vmp.media.zlm.ZLMServerFactory: 101 关闭RTP Server {"code":0,"hit":0} 2024-12-15 23:06:12.656 [async-114] ERROR --- c.g.i.v.g.service.impl.GbChannelPlayServiceImpl: 122 [点播失败] IPC000415(44012628484328000415) java.lang.IllegalArgumentException: Bad code -3         at gov.nist.javax.sip.message.SIPRequest.createResponse(SIPRequest.java:680)         at gov.nist.javax.sip.message.SIPRequest.createResponse(SIPRequest.java:650)         at gov.nist.javax.sip.message.MessageFactoryImpl.createResponse(MessageFactoryImpl.java:504)         at com.genersoft.iot.vmp.gb28181.transmit.event.request.SIPRequestProcessorParent.responseAck(SIPRequestProcessorParent.java:88)         at com.genersoft.iot.vmp.gb28181.transmit.event.request.SIPRequestProcessorParent.responseAck(SIPRequestProcessorParent.java:80)         at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.InviteRequestProcessor.lambda$process$1(InviteRequestProcessor.java:167)         at com.genersoft.iot.vmp.gb28181.service.impl.PlayServiceImpl.play(PlayServiceImpl.java:421)         at com.genersoft.iot.vmp.gb28181.service.impl.PlayServiceImpl.play(PlayServiceImpl.java:1662)         at com.genersoft.iot.vmp.gb28181.service.impl.PlayServiceImpl$$FastClassBySpringCGLIB$$6af2573a.invoke(<generated&gt;)         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)         at com.baomidou.dynamic.datasource.aop.DynamicDataSourceAnnotationInterceptor.invoke(DynamicDataSourceAnnotationInterceptor.java:50)         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)         at com.genersoft.iot.vmp.gb28181.service.impl.PlayServiceImpl$$EnhancerBySpringCGLIB$$6eaccea3.play(<generated&gt;)         at com.genersoft.iot.vmp.gb28181.service.impl.GbChannelPlayServiceImpl.playGbDeviceChannel(GbChannelPlayServiceImpl.java:118)         at com.genersoft.iot.vmp.gb28181.service.impl.GbChannelPlayServiceImpl.play(GbChannelPlayServiceImpl.java:95)         at com.genersoft.iot.vmp.gb28181.service.impl.GbChannelPlayServiceImpl.start(GbChannelPlayServiceImpl.java:42)         at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.InviteRequestProcessor.process(InviteRequestProcessor.java:164)         at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(SIPProcessorObserver.java:80)         at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated&gt;)         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)         at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)         at java.base/java.lang.Thread.run(Thread.java:833)   
我调整了线程池的配置， 你试试
   
麻烦提供下完整的日志,
 wvp-2024-12-17.8.log
 @648540858
