### ISSUE TITLE
上级点击设备录像查询，下级平台"无录像数据"时异常报错了

### ISSUE THREAD

**Issue by Wang112233www** [648540858/wvp-GB28181-pro#401]
都是WVP级联，上级点击设备录像查询，下级平台"无录像数据"时异常报错了。上级平台一直无返回

2022-03-15 18:42:02.075 DEBUG 6 --- [wvp-19] .i.v.g.t.e.r.i.m.MessageRequestProcessor : 接收到消息：MESSAGE sip:34000000002000000001@3400000002 SIP/2.0
Via: SIP/2.0/UDP 192.168.0.64:5060;rport=5060;branch=z9hG4bK679172413;received=192.168.0.64
From: <sip:22245678902000000026@3400000002>;tag=257206901
To: <sip:34000000002000000001@3400000002>
Call-ID: 1007447512
CSeq: 20 MESSAGE
Content-Type: Application/MANSCDP+xml
Max-Forwards: 70
User-Agent: IP Camera
Content-Length: 193

<?xml version="1.0" encoding="GB2312"?>
<Response>
<CmdType>RecordInfo</CmdType>
<SN>271680</SN>
<DeviceID>12345678901320000030</DeviceID>
<Name>Camera 01</Name>
<SumNum>0</SumNum>
</Response>

2022-03-15 18:42:02.076 DEBUG 6 --- [wvp-19] c.g.i.v.s.d.P.getParentPlatByServerGBId  : ==>  Preparing: SELECT * FROM parent_platform WHERE serverGBId=?
2022-03-15 18:42:02.076 DEBUG 6 --- [wvp-19] c.g.i.v.s.d.P.getParentPlatByServerGBId  : ==> Parameters: 22245678902000000026(String)
2022-03-15 18:42:02.077 DEBUG 6 --- [wvp-19] c.g.i.v.s.d.P.getParentPlatByServerGBId  : <==      Total: 0
2022-03-15 18:42:02.082  INFO 6 --- [wvp-19] i.m.r.c.RecordInfoResponseMessageHandler : 无录像数据
2022-03-15 18:42:02.090 ERROR 6 --- [wvp-19] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(javax.sip.RequestEvent)

java.lang.NullPointerException: null
        at com.genersoft.iot.vmp.gb28181.event.record.RecordEndEventListener.onApplicationEvent(RecordEndEventListener.java:36) ~[classes!/:2.0.2]
        at com.genersoft.iot.vmp.gb28181.event.record.RecordEndEventListener.onApplicationEvent(RecordEndEventListener.java:20) ~[classes!/:2.0.2]

**Comment by 648540858** [comment]
已修复
