### ISSUE TITLE
在内部网络环境，所有摄像头通道已获取到，但不更新通道，只更新目录

### ISSUE THREAD

**Issue by mengxing2017** [648540858/wvp-GB28181-pro#432]
**描述错误**
在内部网络环境，所有摄像头通道已获取到，但不更新通道，只更新目录

**如何复现**
刷新通道时，提示通道已获取到，但只更新目录

**预期行为**
所有通道更新

**截图**

**环境信息:**
 - 1. 部署方式 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 - 2. 部署环境 centos 7...
 - 3. 端口开放情况 未开防火墙
 - 4. 是否是公网部署 局域网部署，不连接公网
 - 5. 是否使用https 不启用https

**报错信息**

```
java.net.UnknownHostException: api.map.baidu.com2022-04-10 17:46:15.991 [wvp-6] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler:39 - Unexpected exception occurred invoking async method: public void com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(javax.sip.RequestEvent)
java.lang.NullPointerException: null
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.response.cmd.CatalogResponseMessageHandler.processNotifyMobilePosition(CatalogResponseMessageHandler.java:220)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.response.cmd.CatalogResponseMessageHandler.handForDevice(CatalogResponseMessageHandler.java:119)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageHandlerAbstract.handForDevice(MessageHandlerAbstract.java:28)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageRequestProcessor.process(MessageRequestProcessor.java:105)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(SIPProcessorObserver.java:82)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2022-04-10 17:46:15.991 [wvp-7] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler:39 - Unexpected exception occurred invoking async method: public void com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(javax.sip.RequestEvent)
java.lang.NullPointerException: null
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.response.cmd.CatalogResponseMessageHandler.processNotifyMobilePosition(CatalogResponseMessageHandler.java:220)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.response.cmd.CatalogResponseMessageHandler.handForDevice(CatalogResponseMessageHandler.java:119)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageHandlerAbstract.handForDevice(MessageHandlerAbstract.java:28)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageRequestProcessor.process(MessageRequestProcessor.java:105)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(SIPProcessorObserver.java:82)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-04-10 17:46:15.991 [wvp-16] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler:39 - Unexpected exception occurred invoking async method: public void com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(javax.sip.RequestEvent)
java.lang.NullPointerException: null
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.response.cmd.CatalogResponseMessageHandler.processNotifyMobilePosition(CatalogResponseMessageHandler.java:220)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.response.cmd.CatalogResponseMessageHandler.handForDevice(CatalogResponseMessageHandler.java:119)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageHandlerAbstract.handForDevice(MessageHandlerAbstract.java:28)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageRequestProcessor.process(MessageRequestProcessor.java:105)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(SIPProcessorObserver.java:82)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at java.net.Socket.connect(Socket.java:556)
	at java.net.Socket.<init>(Socket.java:452)
	at java.net.Socket.<init>(Socket.java:229)
	at com.genersoft.iot.vmp.utils.GpsUtil.Wgs84ToBd09(GpsUtil.java:21)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.response.cmd.CatalogResponseMessageHandler.processNotifyMobilePosition(CatalogResponseMessageHandler.java:219)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.response.cmd.CatalogResponseMessageHandler.handForDevice(CatalogResponseMessageHandler.java:119)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageHandlerAbstract.handForDevice(MessageHandlerAbstract.java:28)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageRequestProcessor.process(MessageRequestProcessor.java:105)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(SIPProcessorObserver.java:82)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-04-10 17:46:15.992 [wvp-4] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler:39 - Unexpected exception occurred invoking async method: public void com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(javax.sip.RequestEvent)
java.lang.NullPointerException: null
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.response.cmd.CatalogResponseMessageHandler.processNotifyMobilePosition(CatalogResponseMessageHandler.java:220)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.response.cmd.CatalogResponseMessageHandler.handForDevice(CatalogResponseMessageHandler.java:119)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageHandlerAbstract.handForDevice(MessageHandlerAbstract.java:28)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageRequestProcessor.process(MessageRequestProcessor.java:105)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(SIPProcessorObserver.java:82)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.net.UnknownHostException: api.map.baidu.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at java.net.Socket.connect(Socket.java:556)
	at java.net.Socket.<init>(Socket.java:452)
	at java.net.Socket.<init>(Socket.java:229)
	at com.genersoft.iot.vmp.utils.GpsUtil.Wgs84ToBd09(GpsUtil.java:21)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.response.cmd.CatalogResponseMessageHandler.processNotifyMobilePosition(CatalogResponseMessageHandler.java:219)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.response.cmd.CatalogResponseMessageHandler.handForDevice(CatalogResponseMessageHandler.java:119)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageHandlerAbstract.handForDevice(MessageHandlerAbstract.java:28)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageRequestProcessor.process(MessageRequestProcessor.java:105)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(SIPProcessorObserver.java:82)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
**临时修复**

```shell
diff --git a/src/main/java/com/genersoft/iot/vmp/gb28181/transmit/event/request/impl/message/response/cmd/CatalogResponseMessageHandler.java b/src/main/java/com/genersoft
index cc54ec9..1ede4f1 100644
--- a/src/main/java/com/genersoft/iot/vmp/gb28181/transmit/event/request/impl/message/response/cmd/CatalogResponseMessageHandler.java
+++ b/src/main/java/com/genersoft/iot/vmp/gb28181/transmit/event/request/impl/message/response/cmd/CatalogResponseMessageHandler.java
@@ -115,9 +115,9 @@ public class CatalogResponseMessageHandler extends SIPRequestProcessorParent imp
                             continue;
                         }
                         //by brewswang
-                        if (NumericUtil.isDouble(XmlUtil.getText(itemDevice, "Longitude"))) {//如果包含位置信息，就更新一下位置
-                            processNotifyMobilePosition(evt, itemDevice);
-                        }
+                        //if (NumericUtil.isDouble(XmlUtil.getText(itemDevice, "Longitude"))) {//如果包含位置信息，就更新一下位置
+                        //    processNotifyMobilePosition(evt, itemDevice);
+                        //}
                         
                         DeviceChannel deviceChannel = XmlUtil.channelContentHander(itemDevice);
                         deviceChannel.setDeviceId(device.getDeviceId());
diff --git a/src/main/java/com/genersoft/iot/vmp/service/impl/DeviceServiceImpl.java b/src/main/java/com/genersoft/iot/vmp/service/impl/DeviceServiceImpl.java
index e9f7968..0d422e7 100644
--- a/src/main/java/com/genersoft/iot/vmp/service/impl/DeviceServiceImpl.java
+++ b/src/main/java/com/genersoft/iot/vmp/service/impl/DeviceServiceImpl.java
@@ -58,7 +58,7 @@ public class DeviceServiceImpl implements IDeviceService {
 
     @Override
     public boolean addMobilePositionSubscribe(Device device) {
-        if (device == null || device.getSubscribeCycleForMobilePosition() < 0) {
+        if (device == null || device.getSubscribeCycleForMobilePosition() <= 0) {
             return false;
         }
         if (dynamicTask.contains(device.getDeviceId() + "mobile_position")) {
@@ -79,7 +79,7 @@ public class DeviceServiceImpl implements IDeviceService {
 
     @Override
     public boolean removeMobilePositionSubscribe(Device device) {
-        if (device == null || device.getSubscribeCycleForCatalog() < 0) {
+        if (device == null || device.getSubscribeCycleForCatalog() <= 0) {
             return false;
         }
         logger.info("移除移动位置订阅: {}", device.getDeviceId());
diff --git a/web_src/package-lock.json b/web_src/package-lock.json

```

临时修复后，获取通道、播放视频正常

**Comment by 648540858** [comment]
好的，你也可以测试下现在的代码，应该是内网访问百度API导致的
