### ISSUE TITLE
新版本国际级联NVR,下级推给上级,上级刷不出来录像列表,报空指针异常

### ISSUE THREAD

**Issue by threadroc** [648540858/wvp-GB28181-pro#485]
**描述错误**
2022.5.21编译的最新WVP和ZLM
NVR设备推给下级WVP平台没问题,下级WVP,再国际级联推给上级,上级点录像列表的随便选择一个日期,刷新不出来录像列表,下级WVP日志报空指针异常
RecordInfoResponseMessageHandler 类的145行代码 Collections.sort(recordDataCatch.getRecordInfo(deviceId, sn).getRecordList());

**如何复现**
java.lang.NullPointerException: null
        at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.response.cmd.RecordInfoResponseMessageHandler.releaseRequest(RecordInfoResponseMessageHandler.java:145) ~[classes!/:2.2.1]
        at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.response.cmd.RecordInfoResponseMessageHandler.handForDevice(RecordInfoResponseMessageHandler.java:120) ~[classes!/:2.2.1]
        at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageHandlerAbstract.handForDevice(MessageHandlerAbstract.java:28) ~[classes!/:2.2.1]
        at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageRequestProcessor.process(MessageRequestProcessor.java:118) ~[classes!/:2.2.1]
        at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(SIPProcessorObserver.java:89) ~[classes!/:2.2.1]
        at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>) ~[classes!/:2.2.1]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_181]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_181]

**预期行为**
清晰简洁的描述您期望发生的事情

**截图**

**环境信息:**
公网 端口全开 ubuntu

**Comment by 648540858** [comment]
已修复
