### ISSUE TITLE
录像功能报错

### ISSUE THREAD

**Issue by angel-baal** [648540858/wvp-GB28181-pro#51]
录像功能报错

**Comment by 648540858** [comment]
具体描述下， 做了什么操作， 报的什么错。

**Comment by angel-baal** [comment]
点击设备录像报一下错误
2021-02-06 13:58:13.515  INFO 1572 --- [ool-1-thread-69] c.g.i.v.g.t.r.i.MessageRequestProcessor  : 接收到RecordInfo消息
Exception in thread "pool-1-thread-69" java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:542)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.genersoft.iot.vmp.gb28181.transmit.request.impl.MessageRequestProcessor.processMessageRecordInfo(MessageRequestProcessor.java:316)
        at com.genersoft.iot.vmp.gb28181.transmit.request.impl.MessageRequestProcessor.process(MessageRequestProcessor.java:101)
        at com.genersoft.iot.vmp.gb28181.transmit.request.SIPRequestAbstractProcessor.process(SIPRequestAbstractProcessor.java:35)
        at com.genersoft.iot.vmp.gb28181.SipLayer.lambda$processRequest$0(SipLayer.java:118)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by angel-baal** [comment]
还有就是新版本编译后运行能登录进去，但摄像头获取不了视频

**Comment by 648540858** [comment]
抓个包看下

**Comment by 648540858** [comment]
我先关了
