### ISSUE TITLE
访问RedisUtil 相关方法时redistemplate nullpointer

### ISSUE THREAD

**Issue by zouxiaodong** [648540858/wvp-GB28181-pro#593]
**描述错误**
描述下您遇到的问题
 更新最新代码后(springboot 2.7.2)出现如下问题，springboot 2.3时正常
2022-08-29 11:02:27.625 [wvp-5] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler:39 - Unexpected exception occurred invoking async method: public void com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(javax.sip.RequestEvent)
java.lang.NullPointerException: null
        at com.genersoft.iot.vmp.utils.redis.RedisUtil.scan(RedisUtil.java:730)
        at com.genersoft.iot.vmp.gb28181.session.VideoStreamSessionManager.getSsrcTransaction(VideoStreamSessionManager.java:127)
        at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageRequestProcessor.process(MessageRequestProcessor.java:77)
        at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(SIPProcessorObserver.java:80)

**如何复现**
有明确复现步骤的问题会很容易被解决
  1,启动时，国际设备立即连接WVP就会出现这个问题，
 static {
        redisTemplate = (RedisTemplate) SpringBeanFactory.getBean("redisTemplate");
    }，在执行这个静态块时redisTemplate还没有初始化

**预期行为**
清晰简洁的描述您期望发生的事情
   正确访问redis

**环境信息:**
 - 1. 部署方式 
  最新代码编译安装 
 - 2. 部署环境 

 - 3. 端口开放情况
 - 4. 是否是公网部署
 - 5. 是否使用https
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试

**Comment by zouxiaodong** [comment]
已通过NULL判断再次获取
