### ISSUE TITLE
设备注册成功，通道数0

### ISSUE THREAD

**Issue by xuduogui** [648540858/wvp-GB28181-pro#652]
**描述错误**
`
2022-10-26 18:16:43.287 [main] INFO  c.genersoft.iot.vmp.service.impl.DeviceServiceImpl:97 - [设备上线] deviceId：bkq-ks-124567->192.168.31.64:7060
2022-10-26 18:16:43.302 [main] INFO  c.genersoft.iot.vmp.service.impl.DeviceServiceImpl:138 - [设备上线]: bkq-ks-124567，通道数为0,查询通道信息
Exception in thread "wvp-6" java.lang.NullPointerException
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.response.cmd.CatalogResponseMessageHandler.lambda$handForDevice$0(CatalogResponseMessageHandler.java:98)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-10-26 18:16:43.358 [main] INFO  c.g.iot.vmp.storager.impl.RedisCatchStorageImpl:832 - [redis通知]获取所有推流设备的状态
2022-10-26 18:16:43.363 [main] INFO  com.genersoft.iot.vmp.VManageBootstrap:35 - 构建版本： 2.3.2
2022-10-26 18:16:43.363 [main] INFO  com.genersoft.iot.vmp.VManageBootstrap:36 - 构建时间： 20221026
2022-10-26 18:16:43.364 [main] INFO  com.genersoft.iot.vmp.VManageBootstrap:37 - GIT最后提交时间： 20221025
`
![error](https://user-images.githubusercontent.com/28623710/198029978-ddfdaff0-65a5-42f3-a05d-6c53bc45aea8.png)

**如何复现**
最新项目，直接按照文档部署
之前能够正常工作，今天操作了很多次修改布控球上的id信息、名称信息等，主要修改范围：SIP服务地址、SIP服务器端口、SIP用户名、SIP用户认证ID、SIP用户认证密码、视频通道1编码ID
![device-config](https://user-images.githubusercontent.com/28623710/198043198-40fd6dd8-e8dc-41cb-b811-3c861ca3d546.png)

**预期行为**
能够准确捕获通道

**截图**

**环境信息:**
 - 1. 部署方式 wvp-pro docker / zlm(docker) + 编译wvp-pro/ wvp-prp + zlm都是编译部署/
 部署方式：wvp-pro 开发环境（idea） / zlm（docker）
2022-10-26 18:12:52.296 [main] INFO  com.genersoft.iot.vmp.VManageBootstrap:35 - 构建版本： 2.3.2
2022-10-26 18:12:52.296 [main] INFO  com.genersoft.iot.vmp.VManageBootstrap:36 - 构建时间： 20221026
2022-10-26 18:12:52.296 [main] INFO  com.genersoft.iot.vmp.VManageBootstrap:37 - GIT最后提交时间： 20221025

 - 2. 部署环境 windows / ubuntu/ centos ...
 部署环境：windows11开发环境（idea）

 - 3. 端口开放情况
 端口开放：局域网，关闭防火墙，设备也在局域网

 - 4. 是否是公网部署
 没有使用公网部署

 - 5. 是否使用https
 没有使用https

 - 6. 方便的话提供下使用的设备品牌或平台
 使用的设备：海康布控球
 
 - 7. 你做过哪些尝试
 重启设备、重启服务、重启zlm、重启redis、清空redis
 抓包
 修改源码，忽略错误继续执行（CatalogResponseMessageHandler.java：99 行开始添加下面内容)
 `
 try {
      sumNum = Integer.parseInt(sumNumElement.getText());
  } catch (Exception e) {
      logger.error("补充异常", e);
  }
`

**Comment by xuduogui** [comment]
点击设备刷新按钮的抓包情况附上
[click-refesh-device.zip](https://github.com/648540858/wvp-GB28181-pro/files/9868531/click-refesh-device.zip)

**Comment by xuduogui** [comment]
wvp服务重启，发现了些问题
![catalog-deviceid-not-exist](https://user-images.githubusercontent.com/28623710/198029065-0f08c6a9-1363-4528-9730-7264af3b6352.png)
[wvp-restart.zip](https://github.com/648540858/wvp-GB28181-pro/files/9869524/wvp-restart.zip)

**Comment by xuduogui** [comment]
补充catalog发送和返回数据
发送
![catalog-send](https://user-images.githubusercontent.com/28623710/198038010-3b59c2de-00c8-434e-848c-a18a7bed77e0.png)

返回
![catalog-back](https://user-images.githubusercontent.com/28623710/198038060-a0fa432b-19e3-411c-a80d-48527f2b8040.png)

wvp页面显示
![wvp](https://user-images.githubusercontent.com/28623710/198038130-f5e0e905-e3fa-4662-b9f6-23e45f0c9d89.png)

**Comment by xuduogui** [comment]
这里启动的时候发生异常之后，就永远进不去了，taskQueueHandlerRun的一直为true，不知道有没有影响

![taskQueueHandlerRun-error](https://user-images.githubusercontent.com/28623710/198040368-59973042-a8fe-4d0b-928a-a424dd45fe9a.png)

**Comment by xuduogui** [comment]
期待答复，非常感谢！

**Comment by dht12021** [comment]
亲亲问题解决了吗，我也是一样的问题。

**Comment by NBXianYu** [comment]
通道是0那个，我也遇到了，海康的，因为28181相关配置下面，有一个设备通道编码id配置的，要给通道配置id后，就有了。

**Comment by Gozly** [comment]
更换通道号或者重新输入sip进行配置，刷新再试几次

**Comment by fuyouping** [comment]
> 

设备通道编码id  怎么获取啊，我这边是空白的，随便填写一个，提示参数错误

**Comment by Gozly** [comment]
> 用默认的就可以了，不用更改

**Comment by innocence-awr** [comment]
设备通道编码id 怎么获取啊，我这边是空白的，随便填写一个，提示参数错误
海康设备
IPC的第11位-13位要填写132
NVR的第11位-13位要填写118
