### ISSUE TITLE
启动之后会报redis的错误

### ISSUE THREAD

**Issue by SixSix-God** [648540858/wvp-GB28181-pro#813]
**描述错误**
正常启动之后报redis的错

**如何复现**
有明确复现步骤的问题会很容易被解决

**预期行为**
java.lang.IllegalStateException: LettuceConnectionFactory was destroyed and cannot be used anymore
	at org.springframework.util.Assert.state(Assert.java:76)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.assertInitialized(LettuceConnectionFactory.java:1263)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:414)
	at org.springframework.data.redis.core.RedisConnectionUtils.fetchConnection(RedisConnectionUtils.java:193)
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:144)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:105)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:211)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:191)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:178)
	at com.genersoft.iot.vmp.utils.redis.RedisUtil.scan(RedisUtil.java:30)
	at com.genersoft.iot.vmp.gb28181.session.VideoStreamSessionManager.getSsrcTransaction(VideoStreamSessionManager.java:76)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageRequestProcessor.process(MessageRequestProcessor.java:74)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(SIPProcessorObserver.java:83)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**截图**
![Uploading image.png…]()

**环境信息:**
 - 1. 部署方式 wvp-pro/ wvp-prp + zlm都是编译部署
 - 2. 部署环境 centos ...
 - 3. 端口开放情况 以开放
 - 4. 是否是公网部署 是
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台 海康
 - 7. 你做过哪些尝试

**Comment by penghd** [comment]
最重要的是在你列出来这些日志之前的几条，要贴出来，或者完整运行日志，java报错反而不必要

**Comment by SixSix-God** [comment]
![image](https://user-images.githubusercontent.com/53391873/230773780-a88f2380-faa4-402e-9aa7-bfd2651903a0.png)
![image](https://user-images.githubusercontent.com/53391873/230773816-3b2cdd5a-b746-4b59-9a21-3fba2b49e34c.png)



 _ _   |_  _ _|_. ___ _ |    _ 
| | |\/|_)(_| | |_\  |_)||_|_\ 
     /               |         
                        3.5.3.1 
2023-04-09 20:53:58.178  WARN --- WebSecurity : You are asking Spring Security to ignore Ant [pattern='/']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2023-04-09 20:53:58.179  INFO --- DefaultSecurityFilterChain : Will not secure Ant [pattern='/']
2023-04-09 20:53:58.179  WARN --- WebSecurity : You are asking Spring Security to ignore Ant [pattern='/#/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2023-04-09 20:53:58.179  INFO --- DefaultSecurityFilterChain : Will not secure Ant [pattern='/#/**']
2023-04-09 20:53:58.179  WARN --- WebSecurity : You are asking Spring Security to ignore Ant [pattern='/static/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2023-04-09 20:53:58.179  INFO --- DefaultSecurityFilterChain : Will not secure Ant [pattern='/static/**']
2023-04-09 20:53:58.179  WARN --- WebSecurity : You are asking Spring Security to ignore Ant [pattern='/index.html']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2023-04-09 20:53:58.180  INFO --- DefaultSecurityFilterChain : Will not secure Ant [pattern='/index.html']
2023-04-09 20:53:58.180  WARN --- WebSecurity : You are asking Spring Security to ignore Ant [pattern='/doc.html']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2023-04-09 20:53:58.180  INFO --- DefaultSecurityFilterChain : Will not secure Ant [pattern='/doc.html']
2023-04-09 20:53:58.180  WARN --- WebSecurity : You are asking Spring Security to ignore Ant [pattern='/webjars/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2023-04-09 20:53:58.180  INFO --- DefaultSecurityFilterChain : Will not secure Ant [pattern='/webjars/**']
2023-04-09 20:53:58.180  WARN --- WebSecurity : You are asking Spring Security to ignore Ant [pattern='/swagger-resources/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2023-04-09 20:53:58.180  INFO --- DefaultSecurityFilterChain : Will not secure Ant [pattern='/swagger-resources/**']
2023-04-09 20:53:58.180  WARN --- WebSecurity : You are asking Spring Security to ignore Ant [pattern='/v3/api-docs/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2023-04-09 20:53:58.180  INFO --- DefaultSecurityFilterChain : Will not secure Ant [pattern='/v3/api-docs/**']
2023-04-09 20:53:58.180  WARN --- WebSecurity : You are asking Spring Security to ignore Ant [pattern='/js/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2023-04-09 20:53:58.180  INFO --- DefaultSecurityFilterChain : Will not secure Ant [pattern='/js/**']
2023-04-09 20:53:58.180  WARN --- WebSecurity : You are asking Spring Security to ignore Ant [pattern='/api/device/query/snap/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2023-04-09 20:53:58.180  INFO --- DefaultSecurityFilterChain : Will not secure Ant [pattern='/api/device/query/snap/**']
2023-04-09 20:53:58.180  WARN --- WebSecurity : You are asking Spring Security to ignore Ant [pattern='/record_proxy/*/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2023-04-09 20:53:58.180  INFO --- DefaultSecurityFilterChain : Will not secure Ant [pattern='/record_proxy/*/**']
2023-04-09 20:53:58.180  WARN --- WebSecurity : You are asking Spring Security to ignore Ant [pattern='/api/v1/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2023-04-09 20:53:58.180  INFO --- DefaultSecurityFilterChain : Will not secure Ant [pattern='/api/v1/**']
2023-04-09 20:53:58.205  INFO --- DefaultSecurityFilterChain : Will secure any request with [org.springframework.security.web.session.DisableEncodeUrlFilter@15c25153, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@1252b961, org.springframework.security.web.context.SecurityContextPersistenceFilter@4de41af9, org.springframework.security.web.header.HeaderWriterFilter@6e1d8f9e, org.springframework.web.filter.CorsFilter@9ed238c, org.springframework.security.web.authentication.logout.LogoutFilter@38be305c, com.genersoft.iot.vmp.conf.security.JwtAuthenticationFilter@78d6692f, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@47404bea, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@5d018107, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@56276db8, org.springframework.security.web.session.SessionManagementFilter@62fe6067, org.springframework.security.web.access.ExceptionTranslationFilter@2dbe250d, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@1c80e49b]
2023-04-09 20:53:58.356  INFO --- WelcomePageHandlerMapping : Adding welcome page: class path resource [static/index.html]
2023-04-09 20:53:59.841  INFO --- Http11NioProtocol : Starting ProtocolHandler ["http-nio-18080"]
2023-04-09 20:53:59.865  INFO --- TomcatWebServer : Tomcat started on port(s): 18080 (http) with context path ''
2023-04-09 20:53:59.867  INFO --- ServiceInfo : 项目启动获取启动的端口号:  18080
2023-04-09 20:54:00.152  INFO --- [/] : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-04-09 20:54:00.152  INFO --- DispatcherServlet : Initializing Servlet 'dispatcherServlet'
2023-04-09 20:54:00.154  INFO --- DispatcherServlet : Completed initialization in 2 ms
2023-04-09 20:54:00.335  INFO --- VManageBootstrap : Started VManageBootstrap in 6.952 seconds (JVM running for 7.457)
2023-04-09 20:54:00.337  INFO --- AlarmNotifyMessageHandler : [SIP日志]已开启
2023-04-09 20:54:00.363  INFO --- StackLoggerImpl : value 60000 will be used for reliableConnectionKeepAliveTimeout stack property
2023-04-09 20:54:00.364  INFO --- StackLoggerImpl : Setting Stack Thread priority to 10
2023-04-09 20:54:00.368  WARN --- StackLoggerImpl : using default tls security policy
2023-04-09 20:54:00.370  WARN --- StackLoggerImpl : Using default keystore type jks
2023-04-09 20:54:00.370  WARN --- StackLoggerImpl : TLS server settings will be inactive - TLS key store will use JVM defaults keyStoreType=jks javax.net.ssl.keyStore=null javax.net.ssl.keyStorePassword=null
2023-04-09 20:54:00.370  INFO --- StackLoggerImpl : javax.net.ssl.trustStorePassword is null, using the password passed through javax.net.ssl.keyStorePassword
2023-04-09 20:54:00.370  WARN --- StackLoggerImpl : Using default truststore type jks
2023-04-09 20:54:00.370  WARN --- StackLoggerImpl : TLS trust settings will be inactive - TLS trust store will use JVM defaults. trustStoreType=jks javax.net.ssl.trustStore=null javax.net.ssl.trustStorePassword=null
2023-04-09 20:54:00.423  INFO --- HikariDataSource : HikariPool-1 - Starting...
2023-04-09 20:54:00.427  INFO --- StackLoggerImpl : the sip stack timer gov.nist.javax.sip.stack.timers.DefaultSipTimer has been started
2023-04-09 20:54:00.459  INFO --- SipLayer : [Sip Server] tcp://10.168.168.185:5090 启动成功
2023-04-09 20:54:00.464  INFO --- SipLayer : [Sip Server] udp://10.168.168.185:5090 启动成功
2023-04-09 20:54:00.672  INFO --- HikariDataSource : HikariPool-1 - Start completed.
2023-04-09 20:54:00.720  WARN --- MediaServerServiceImpl : [更新ZLM 保活信息]失败，未找到流媒体信息
2023-04-09 20:54:00.822  INFO --- ZLMRunner : [zlm] 等待默认zlm中...
2023-04-09 20:54:00.825  INFO --- MediaServerServiceImpl : [zlm] 缓存初始化 
2023-04-09 20:54:01.056  INFO --- MediaServerServiceImpl : [ZLM] 正在连接 : a52d61e9-d6d7-4c14-8ecf-cd392419107c -> 10.168.168.44:8090
2023-04-09 20:54:01.112 ERROR --- AssistRESTfulUtils : 连接Assist失败: Connection refused (Connection refused), Failed to connect to /10.168.168.44:18081
2023-04-09 20:54:01.113  INFO --- AssistRESTfulUtils : 请检查media配置并确认Assist已启动...
2023-04-09 20:54:01.113  INFO --- MediaServerServiceImpl : [ZLM] 正在设置 ：a52d61e9-d6d7-4c14-8ecf-cd392419107c -> 10.168.168.44:8090
2023-04-09 20:54:01.115  INFO --- MediaServerServiceImpl : [ZLM] 设置成功 a52d61e9-d6d7-4c14-8ecf-cd392419107c -> 10.168.168.44:8090
2023-04-09 20:54:01.120  INFO --- MediaServerServiceImpl : [ZLM] 连接成功 a52d61e9-d6d7-4c14-8ecf-cd392419107c - 10.168.168.44:8090 
2023-04-09 20:54:01.123  INFO --- ZLMStatusEventListener : [ZLM] 上线 ID：a52d61e9-d6d7-4c14-8ecf-cd392419107c
2023-04-09 20:54:01.150  INFO --- valuationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-04-09 20:54:01.164  INFO --- StreamProxyServiceImpl : 恢复流代理，3QHCA5613400HN4/41092701801327000229
2023-04-09 20:54:01.174 ERROR --- SpringApplication : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:774)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.genersoft.iot.vmp.VManageBootstrap.main(VManageBootstrap.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.NullPointerException: null
	at com.genersoft.iot.vmp.conf.SipPlatformRunner.run(SipPlatformRunner.java:52)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
	... 13 common frames omitted

2023-04-09 20:54:09.118  INFO --- MediaServerServiceImpl : [zlm心跳到期]：a52d61e9-d6d7-4c14-8ecf-cd392419107c
2023-04-09 20:54:09.121  INFO --- MediaServerServiceImpl : [zlm心跳到期]：a52d61e9-d6d7-4c14-8ecf-cd392419107c验证后zlm仍在线，恢复心跳信息,请检查zlm是否可以正常向wvp发送心跳
2023-04-09 20:54:09.219 ERROR --- TaskUtils$LoggingErrorHandler : Unexpected error occurred in scheduled task

org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 10.168.168.185:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.translateException(LettuceConnectionFactory.java:1689)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1597)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1383)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:1366)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedConnection(LettuceConnectionFactory.java:1093)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:421)
	at org.springframework.data.redis.core.RedisConnectionUtils.fetchConnection(RedisConnectionUtils.java:193)
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:144)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:105)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:211)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:191)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:97)
	at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:54)
	at com.genersoft.iot.vmp.utils.JsonUtil.redisJsonToObject(JsonUtil.java:28)
	at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl.getOne(MediaServerServiceImpl.java:295)
	at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl.updateMediaServerKeepalive(MediaServerServiceImpl.java:702)
	at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl$KeepAliveTimeoutRunnable.run(MediaServerServiceImpl.java:459)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 10.168.168.185:6379
	at org.springframework.data.redis.connection.lettuce.LettucePoolingConnectionProvider.getConnection(LettucePoolingConnectionProvider.java:109)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1595)
	... 23 common frames omitted
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to 10.168.168.185:6379
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:330)
	at io.lettuce.core.RedisClient.connect(RedisClient.java:216)
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:115)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:115)
	at org.springframework.data.redis.connection.lettuce.LettucePoolingConnectionProvider.lambda$null$0(LettucePoolingConnectionProvider.java:97)
	at io.lettuce.core.support.ConnectionPoolSupport$RedisPooledObjectFactory.create(ConnectionPoolSupport.java:211)
	at io.lettuce.core.support.ConnectionPoolSupport$RedisPooledObjectFactory.create(ConnectionPoolSupport.java:201)
	at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:70)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
	at io.lettuce.core.support.ConnectionPoolSupport$1.borrowObject(ConnectionPoolSupport.java:122)
	at io.lettuce.core.support.ConnectionPoolSupport$1.borrowObject(ConnectionPoolSupport.java:117)
	at org.springframework.data.redis.connection.lettuce.LettucePoolingConnectionProvider.getConnection(LettucePoolingConnectionProvider.java:103)
	... 24 common frames omitted
Caused by: java.lang.IllegalStateException: executor not accepting a task
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:61)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:194)
	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted

**Comment by SixSix-God** [comment]
这个是完整的日志，并且这个错误会在重启几次之后恢复正常

**Comment by 648540858** [comment]
请把日志以文件的形式上传，你这样放上来没法看，至少也用语法包裹下，类似这样的
```
我是日志我是日志我是日志我是日志我是日志
```

**Comment by 648540858** [comment]
这里的空指针我修复了

**Comment by 648540858** [comment]
你可以测试下

**Comment by SixSix-God** [comment]
测试了，是修复了，谢谢
