### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by SnailShelled** [648540858/wvp-GB28181-pro#840]
**环境信息:**

 - 1. 部署方式 wvp-prp + zlm都是编译部署/
 - 2. 部署环境 centos 
 - 3. 端口开放情况 都开放了
 - 4. 是否是公网部署 在公网
 - 5. 是否使用https 
 - 6. 方便的话提供下使用的设备品牌或平台 海康的
 - 7. 你做过哪些尝试 本地部署调试代码但是做内网穿透有问题
 - 8. 代码更新时间 最新代码 2023-5-6

**内容描述:**
环境都部署好了，启动后等待海康那边发来连接，总是报认证错误，配置应该都是对的，按照教程一步步来的
  
**日志**
```
2023-05-08 10:32:19.477 ERROR --- GB28181_SIP : gov.nist.javax.sip.stack.IOHandler.sendBytes(IOHandler.java:314) [Problem connecting /202.60.134.185 22072 /0.0.0.0 for message SIP/2.0 401 Unauthorized
CSeq: 1 REGISTER
Call-ID: 6026917
From: <sip:44010200492000000001@4401020049>;tag=1196827831
To: <sip:44010200492000000001@4401020049>
Via: SIP/2.0/TCP 10.139.154.233:60287;rport=22072;branch=z9hG4bK1491592759;received=202.60.134.185
WWW-Authenticate: Digest realm="4401020049",qop="auth",nonce="5f0f6990c68f95f2a048c8df4cea745a",algorithm=MD5
User-Agent: WVP-Pro 
Content-Length: 0

]
2023-05-08 10:32:19.477  WARN --- GB28181_SIP : Failed to connect /202.60.134.185:22072 but trying the advertised port=60287 if it's different than the port we just failed on
2023-05-08 10:32:19.479 ERROR --- RegisterRequestProcessor : 未处理的异常 

javax.sip.SipException: Could not connect to /202.60.134.185:22072
	at gov.nist.javax.sip.SipProviderImpl.sendResponse(SipProviderImpl.java:846)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPSender.transmitRequest(SIPSender.java:91)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPSender.transmitRequest(SIPSender.java:42)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.RegisterRequestProcessor.process(RegisterRequestProcessor.java:126)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(SIPProcessorObserver.java:83)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by 648540858** [comment]
看日志是自动识别的海康平台为202.60.134.185:22072，但是无法连接，消息发不过去，你可以自己排查下网络情况

**Comment by SnailShelled** [comment]
感谢您的回复，我想了解下这个网络情况是我的摄像头设备的还是我腾讯云的，我这边有大华的设备显示能显示在线和通道，但是没法正常拉流播放
![image](https://user-images.githubusercontent.com/43066669/236730284-1552800b-27b4-4270-9fe4-35f04729b867.png)

**Comment by SnailShelled** [comment]
![image](https://user-images.githubusercontent.com/43066669/236730556-5053b7be-489f-4ee3-bf7f-e60ed875070c.png)

**Comment by 648540858** [comment]
这是两个问题，别放在一个issue里提问，另外标题处理下。
