### ISSUE TITLE
BUG 配置了上级平台后重启，上级平台无法连接的话无法启动

### ISSUE THREAD

**Issue by DrunkLife** [648540858/wvp-GB28181-pro#862]
配置了上级平台后重启，上级平台无法连接的话无法启动成功

**Comment by mengxing2017** [comment]
这种问题没有任何意义，要啥没啥

**Comment by DrunkLife** [comment]
2023-05-25 13:46:32.965  WARN --- GB28181_SIP : Failed to connect /*.*.*.*:5060 but trying the advertised port=5060 if it's different than the port we just failed on
2023-05-25 13:46:32.968 ERROR --- GB28181_SIP : Error is 

java.io.IOException: Could not connect to /*.*.*.*:5060
	at gov.nist.javax.sip.stack.IOHandler.sendBytes(IOHandler.java:391)
	at gov.nist.javax.sip.stack.TCPMessageChannel.sendMessage(TCPMessageChannel.java:350)
	at gov.nist.javax.sip.stack.MessageChannel.sendMessage(MessageChannel.java:259)
	at gov.nist.javax.sip.SipProviderImpl.sendRequest(SipProviderImpl.java:746)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPSender.transmitRequest(SIPSender.java:89)
	at com.genersoft.iot.vmp.gb28181.transmit.cmd.impl.SIPCommanderFroPlatform.register(SIPCommanderFroPlatform.java:133)
	at com.genersoft.iot.vmp.gb28181.transmit.cmd.impl.SIPCommanderFroPlatform.unregister(SIPCommanderFroPlatform.java:86)
	at com.genersoft.iot.vmp.conf.SipPlatformRunner.run(SipPlatformRunner.java:53)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.genersoft.iot.vmp.VManageBootstrap.main(VManageBootstrap.java:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)

2023-05-25 13:46:32.973  INFO --- valuationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-05-25 13:46:33.009 ERROR --- SpringApplication : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:774)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.genersoft.iot.vmp.VManageBootstrap.main(VManageBootstrap.java:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: javax.sip.SipException: IO Exception occured while Sending Request
	at gov.nist.javax.sip.SipProviderImpl.sendRequest(SipProviderImpl.java:765)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPSender.transmitRequest(SIPSender.java:89)
	at com.genersoft.iot.vmp.gb28181.transmit.cmd.impl.SIPCommanderFroPlatform.register(SIPCommanderFroPlatform.java:133)
	at com.genersoft.iot.vmp.gb28181.transmit.cmd.impl.SIPCommanderFroPlatform.unregister(SIPCommanderFroPlatform.java:86)
	at com.genersoft.iot.vmp.conf.SipPlatformRunner.run(SipPlatformRunner.java:53)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
	... 13 common frames omitted
Caused by: java.io.IOException: Could not connect to /*.*.*.*:5060
	at gov.nist.javax.sip.stack.IOHandler.sendBytes(IOHandler.java:391)
	at gov.nist.javax.sip.stack.TCPMessageChannel.sendMessage(TCPMessageChannel.java:350)
	at gov.nist.javax.sip.stack.MessageChannel.sendMessage(MessageChannel.java:259)
	at gov.nist.javax.sip.SipProviderImpl.sendRequest(SipProviderImpl.java:746)
	... 18 common frames omitted

2023-05-25 13:46:33.053 ERROR --- SystemInfoUtils : [线程休眠失败] : sleep interrupted
2023-05-25 13:46:33.071  INFO --- HikariDataSource : HikariPool-1 - Shutdown initiated...
2023-05-25 13:46:33.084  INFO --- HikariDataSource : HikariPool-1 - Shutdown completed.
2023-05-25 13:46:34.790 ERROR --- TaskUtils$LoggingErrorHandler : Unexpected error occurred in scheduled task

java.lang.IllegalStateException: LettuceConnectionFactory was destroyed and cannot be used anymore
	at org.springframework.util.Assert.state(Assert.java:76)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.assertInitialized(LettuceConnectionFactory.java:1263)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:414)
	at org.springframework.data.redis.core.RedisConnectionUtils.fetchConnection(RedisConnectionUtils.java:193)
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:144)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:105)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:211)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:191)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:97)
	at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:54)
	at com.genersoft.iot.vmp.utils.JsonUtil.redisJsonToObject(JsonUtil.java:28)
	at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl.getOne(MediaServerServiceImpl.java:282)
	at com.genersoft.iot.vmp.media.zlm.ZLMRunner.getMediaServerConfig(ZLMRunner.java:152)
	at com.genersoft.iot.vmp.media.zlm.ZLMRunner.lambda$connectZlmServer$2(ZLMRunner.java:136)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-05-25 13:46:36.790 ERROR --- TaskUtils$LoggingErrorHandler : Unexpected error occurred in scheduled task

java.lang.IllegalStateException: LettuceConnectionFactory was destroyed and cannot be used anymore
	at org.springframework.util.Assert.state(Assert.java:76)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.assertInitialized(LettuceConnectionFactory.java:1263)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:414)
	at org.springframework.data.redis.core.RedisConnectionUtils.fetchConnection(RedisConnectionUtils.java:193)
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:144)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:105)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:211)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:191)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:97)
	at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:54)
	at com.genersoft.iot.vmp.utils.JsonUtil.redisJsonToObject(JsonUtil.java:28)
	at com.genersoft.iot.vmp.service.impl.MediaServerServiceImpl.getOne(MediaServerServiceImpl.java:282)
	at com.genersoft.iot.vmp.media.zlm.ZLMRunner.getMediaServerConfig(ZLMRunner.java:152)
	at com.genersoft.iot.vmp.media.zlm.ZLMRunner.lambda$connectZlmServer$2(ZLMRunner.java:136)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mengxing2017** [comment]
配置文件错误

**Comment by liwenyan703** [comment]
我也遇到了这个问题，你怎么解决的

**Comment by DrunkLife** [comment]
> 我也遇到了这个问题，你怎么解决的

 没解决，等上级平台恢复后在启动的
