### ISSUE TITLE
使用两个wvp进行国标级联，通过上级的wvp进行点播时下级wvp报空指针异常

### ISSUE THREAD

**Issue by yand9807** [648540858/wvp-GB28181-pro#864]
**环境信息:**

 - 1. 部署方式 wvp-pro docker +  zlm(docker)
 - 2. 部署环境 欧拉
 - 3. 端口开放情况 6060+40000，使用的是单端口模式
 - 4. 是否是公网部署  内网部署
 - 5. 是否使用https 否
 - 6. 方便的话提供下使用的设备品牌或平台
 - 7. 你做过哪些尝试 尝试将代码中写成null的地方附上值，赋值后不在报错，但会提示推流失败，看日志似乎流ID发生了变化
 - 8. 代码更新时间 2023-05-19

**描述错误**
使用两个wvp进行国标级联，通过上级的wvp进行点播时下级wvp报空指针异常
以下为wvp-1的错误日志
<details>
<summary>展开查看详细日志</summary>
<pre>
2023-05-25 08:54:44.954  INFO --- PlayServiceImpl : [点播开始] deviceId: 37010200492000000888, channelId: 37011322001310116866,收流端口：40000, 收流模式：TCP-PASSIVE, SSRC: 0102003187, SSRC校验：true
2023-05-25 08:54:44.955  INFO --- SIPCommander : 061471F3 分配的ZLM为: GyorMepTMeq5vSIo [172.20.88.235:40000]
2023-05-25 08:54:45.807  INFO --- InviteResponseProcessor : [回复ack] 37011322001310116866-> 172.17.0.1:57859 
2023-05-25 08:54:45.808  INFO --- PlayServiceImpl : [点播消息] 收到invite 200, 发现下级自定义了ssrc: 0102005150
2023-05-25 08:54:45.809  INFO --- PlayServiceImpl : [点播消息] SSRC修正 0102003187->0102005150
2023-05-25 08:54:45.824  INFO --- ZLMHttpHookListener : [ZLM HOOK]推流鉴权：GyorMepTMeq5vSIo->rtp://10.211.138.144:11630/rtp/0614799E?
2023-05-25 08:54:45.866  INFO --- ZLMHttpHookListener : [ZLM HOOK] 流注册, GyorMepTMeq5vSIo->fmp4->rtp/0614799E
2023-05-25 08:54:45.866  INFO --- ZLMHttpHookListener : [ZLM HOOK] 流注册, GyorMepTMeq5vSIo->rtsp->rtp/0614799E
2023-05-25 08:54:45.868  INFO --- PlayServiceImpl : [ZLM HOOK] ssrc修正后收到订阅消息： {"aliveSecond":0,"app":"rtp","bytesSpeed":0,"createStamp":1685004885,"docker":false,"mediaServerId":"GyorMepTMeq5vSIo","originSock":{"identifier":"0614799E","local_ip":"172.17.0.3","local_port":40000,"peer_ip":"10.211.138.144","peer_port":11630},"originType":3,"originTypeStr":"rtp_push","originUrl":"rtp://__defaultVhost__/rtp/0614799E","regist":true,"schema":"rtsp","stream":"0614799E","totalReaderCount":"0","tracks":[{"channels":0,"codecId":0,"codecType":0,"fps":25,"height":1536,"ready":true,"sampleBit":0,"sampleRate":0,"width":2048}],"vhost":"__defaultVhost__"}
Exception in thread "wvp-6" java.lang.NullPointerException
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.InviteRequestProcessor.lambda$process$1(InviteRequestProcessor.java:382)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.InviteRequestProcessor.lambda$process$5(InviteRequestProcessor.java:502)
	at com.genersoft.iot.vmp.service.impl.PlayServiceImpl.lambda$play$2(PlayServiceImpl.java:369)
	at com.genersoft.iot.vmp.media.zlm.ZLMHttpHookListener.lambda$onStreamChanged$5(ZLMHttpHookListener.java:309)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-05-25 08:54:45.906  INFO --- ZLMHttpHookListener : [ZLM HOOK] 流注册, GyorMepTMeq5vSIo->rtmp->rtp/0614799E
2023-05-25 08:54:45.906  INFO --- ZLMHttpHookListener : [ZLM HOOK] 流注册, GyorMepTMeq5vSIo->ts->rtp/0614799E
2023-05-25 08:54:47.827  INFO --- ZLMHttpHookListener : [ZLM HOOK] 流注册, GyorMepTMeq5vSIo->hls->rtp/0614799E

</pre>
</details>

**如何复现**
有明确复现步骤的问题会很容易被解决

**截图**  
通过查看代码发现，在PlayServiceImpl中这个位置传了个null，看起来好像是这里引起的
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/53848372/9adfde91-bb40-4b68-91e5-a90cb6d5eca7)
更改后的日志如下：
![image](https://github.com/648540858/wvp-GB28181-pro/assets/53848372/587cadcb-598a-4ed7-9eb7-66686fe78f7d)

**Comment by 648540858** [comment]
已修复
