### ISSUE TITLE
[兼容] 同步海康通道失败，解析XML乱码异常

### ISSUE THREAD

**Issue by guo522593280** [648540858/wvp-GB28181-pro#903]
**描述错误**
本地搭建wvp，能够正常发现海康设备，但是同步通道一直失败，查看日志发现解析XML异常，原因是<Address> 有乱码，修改字符集编码格式还是无法解决。

**截图**  
![1687154369378](https://github.com/648540858/wvp-GB28181-pro/assets/44258983/88115916-a2e8-47ad-835e-2ee9f6a7cb27)
![1687154427133](https://github.com/648540858/wvp-GB28181-pro/assets/44258983/1ad81d65-f305-44af-9596-1acdf726e4fb)

**日志**
```
<?xml version="1.0" encoding="gb2312"?>
<Response>
<CmdType>Catalog</CmdType>
<SN>726289</SN>
<DeviceID>34020000001110000001</DeviceID>
<SumNum>1</SumNum>
<DeviceList Num="1">
<Item>
<DeviceID>34020000001320000001</DeviceID>
<Name>Camera 01</Name>
<Manufacturer>Manufacturer</Manufacturer>
<Model>Camera</Model>
<Owner>Owner</Owner>
<CivilCode>CivilCode</CivilCode>
<Address>??<KP?<K?'@?'@?f/@P?<KL?</Address>
<Parental>0</Parental>
<SafetyWay>0</SafetyWay>
<RegisterWay>1</RegisterWay>
<Secrecy>0</Secrecy>
<Status>ON</Status>
</Item>
</DeviceList>
</Response>

Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@11c9a14d] was not registered for synchronization because synchronization is not active
JDBC Connection [HikariProxyConnection@1959498167 wrapping com.mysql.cj.jdbc.ConnectionImpl@3005db4a] will not be managed by Spring
==>  Preparing: SELECT * FROM wvp_platform WHERE server_gb_id=?
==> Parameters: 34020000001110000001(String)
<==      Total: 0
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@11c9a14d]
2023-06-19 11:35:47.957  WARN --- MessageRequestProcessor : 解析XML消息内容异常

org.dom4j.DocumentException: Error on line 15 of document  : Element type "KP" must be followed by either attribute specifications, ">" or "/>".
	at org.dom4j.io.SAXReader.read(SAXReader.java:511)
	at org.dom4j.io.SAXReader.read(SAXReader.java:392)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.SIPRequestProcessorParent.getRootElement(SIPRequestProcessorParent.java:202)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.SIPRequestProcessorParent.getRootElement(SIPRequestProcessorParent.java:165)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.MessageRequestProcessor.process(MessageRequestProcessor.java:107)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver.processRequest(SIPProcessorObserver.java:83)
	at com.genersoft.iot.vmp.gb28181.transmit.SIPProcessorObserver$$FastClassBySpringCGLIB$$4a3dcb3e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.xml.sax.SAXParseException: Element type "KP" must be followed by either attribute specifications, ">" or "/>".
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:399)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:326)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1466)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.seekCloseOfStartTag(XMLDocumentFragmentScannerImpl.java:1393)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:242)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2783)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:601)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642)
	at org.dom4j.io.SAXReader.read(SAXReader.java:494)
	... 15 common frames omitted
```
**请教，这种情况要怎么配置！！！**

**Comment by 648540858** [comment]
目前解决不了，xml内容不符合规范

**Comment by 648540858** [comment]
修复了你试试，有问题你再打开
