### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by hx20105748** [648540858/wvp-GB28181-pro#971]
2023-07-28 09:57:14.883 ERROR --- lePositionNotifyMessageHandler : [移动位置通知] 异常内容： 

java.time.format.DateTimeParseException: Text '2023-07-28T09:57:10' could not be parsed at index 10
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1874)
	at com.genersoft.iot.vmp.utils.DateUtil.yyyy_MM_dd_HH_mm_ssToISO8601(DateUtil.java:49)
	at com.genersoft.iot.vmp.gb28181.transmit.event.request.impl.message.notify.cmd.MobilePositionNotifyMessageHandler.lambda$handForDevice$0(MobilePositionNotifyMessageHandler.java:147)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by 648540858** [comment]
已修复
